import type { HarnessCard, HarnessDeck, HarnessSelection } from '@/types/dailyHarness';

export const HARNESS_CARDS: HarnessCard[] = [
  {
    id: 'v-ace-standard',
    deck: 'vision',
    title: 'ACE標準化',
    subtitle: '日本のアスリート教育のデフォルトにする',
    active: true,
    baseWeight: 1,
    question: 'ACEが当たり前になった世界で、アスリート教育は何が変わっている？',
    ignitionWords: ['教育のOS', '脳のアップデート', '日本代表の再定義'],
  },
  {
    id: 'v-system-autonomous',
    deck: 'vision',
    title: 'システム自走',
    subtitle: 'MASAが常時いなくても価値が循環する',
    active: true,
    baseWeight: 1,
    question: '自分が今日手を離しても回る形にするなら、何を仕組みに変える？',
    ignitionWords: ['自動化', '標準化', '再利用', 'AI協働'],
  },
  {
    id: 'v-philosophy-legacy',
    deck: 'vision',
    title: '哲学継承',
    subtitle: '思想・経験・問いを次世代へ残す',
    active: true,
    baseWeight: 1,
    question: '今日の経験を、13歳の次世代にも届く形へ変えるなら？',
    ignitionWords: ['志', '原体験', '問い', '後世'],
  },
  {
    id: 't-comparison-neuroscience',
    deck: 'theme',
    title: '比較の脳科学',
    subtitle: '扁桃体・報酬系・比較三原則',
    active: true,
    baseWeight: 1,
    question: '比較が自動で起きた瞬間、身体と認知では何が起きている？',
    ignitionWords: ['順位付け', 'SNS比較', '勝ち負けの外側'],
  },
  {
    id: 't-esteem-vs-efficacy',
    deck: 'theme',
    title: '自尊心 vs 自己効力感',
    subtitle: '自分の価値と「できる感」を分ける',
    active: true,
    baseWeight: 1,
    question: '自分の価値まで結果と結びつけていないか？',
    ignitionWords: ['価値', 'できる感', '結果との分離'],
  },
  {
    id: 't-japanese-os-reboot',
    deck: 'theme',
    title: '日本語OS再起動',
    subtitle: '言葉から認知の選択肢を増やす',
    active: true,
    baseWeight: 1,
    question: '普段使う言葉が、可能性を狭めていないか？',
    ignitionWords: ['言葉', '認知', '再定義'],
  },
  {
    id: 't-layer0-experience',
    deck: 'theme',
    title: 'Layer0 体験設計',
    subtitle: '説明前に身体で気づかせる',
    active: true,
    baseWeight: 1,
    question: '説明せずに体験だけで気づかせるなら、何をする？',
    ignitionWords: ['片足立ち', '感覚', '事実と解釈'],
  },
  {
    id: 't-be-do-have-spiral',
    deck: 'theme',
    title: 'be-do-have スパイラル',
    subtitle: '在り方・行動・所有を循環で捉える',
    active: true,
    baseWeight: 1,
    question: 'haveを終点ではなく次のbeの環境にするなら？',
    ignitionWords: ['habere', '習慣', '循環'],
  },
  {
    id: 't-del1-can',
    deck: 'theme',
    title: 'DEL-1 × can思想',
    subtitle: '老化研究と「できる」の再設計',
    active: true,
    baseWeight: 1,
    question: '身体の制約と認知の制約をどう分けて扱う？',
    ignitionWords: ['老化', 'can', '制約', '可塑性'],
  },
  {
    id: 't-serotonin-base',
    deck: 'theme',
    title: 'セロトニン基盤',
    subtitle: '睡眠・光・リズム・心身基盤',
    active: true,
    baseWeight: 1,
    question: '高い目標の前に整えるべき基盤は何か？',
    ignitionWords: ['睡眠', '朝日', 'リズム', '基盤'],
  },
  {
    id: 't-predictive-coding',
    deck: 'theme',
    title: '予測符号化',
    subtitle: '予測と現実のズレを学習へ変える',
    active: true,
    baseWeight: 1,
    question: '予想外を失敗ではなく更新信号として扱えるか？',
    ignitionWords: ['予測誤差', '時間知覚', '更新'],
  },
  {
    id: 't-goun',
    deck: 'theme',
    title: '五蘊',
    subtitle: '仏教認知モデルとACE Layerの接続',
    active: true,
    baseWeight: 1,
    question: '「自分」と思っているものを要素に分けると何が残る？',
    ignitionWords: ['色受想行識', '観測', '無固定'],
  },
  {
    id: 't-flow-v2',
    deck: 'theme',
    title: 'FLOW v2',
    subtitle: 'Feel → Lived story → Overwrite → Welcome in',
    active: true,
    baseWeight: 1,
    question: '今どのフェーズにいて、次に何を上書きすべきか？',
    ignitionWords: ['Feel', 'Story', 'Overwrite', 'Welcome'],
  },
  {
    id: 't-goodwill-control',
    deck: 'theme',
    title: '善意の無自覚なコントロール',
    subtitle: '良かれと思う介入を観測する',
    active: true,
    baseWeight: 1,
    question: '助けるつもりが相手の自己決定を奪っていないか？',
    ignitionWords: ['善意', 'コントロール', '自己決定'],
  },
  {
    id: 't-message-to-13',
    deck: 'theme',
    title: '13歳の自分に伝えたいこと',
    subtitle: 'ACE思想を原体験へ圧縮する',
    active: true,
    baseWeight: 1,
    question: '13歳の自分なら、今日の話をどう受け取る？',
    ignitionWords: ['原体験', '次世代', '伝わる言葉'],
  },
  {
    id: 't-lien-design',
    deck: 'theme',
    title: 'リアン設計',
    subtitle: '固定分類せず、本人が握るものを選び直す',
    active: true,
    baseWeight: 1,
    question: 'この人が自分で観測し選べる余白は残っているか？',
    ignitionWords: ['結び', '学び', '自己選択'],
  },
  {
    id: 'm-x-post',
    deck: 'medium',
    title: 'Xポスト',
    subtitle: '1投稿で完結する刺し',
    active: true,
    baseWeight: 1.4,
    question: 'このテーマをXの制約があるからこそ、どう伝える？',
    ignitionWords: ['1論点', '短く', '会話誘発'],
  },
  {
    id: 'm-x-thread',
    deck: 'medium',
    title: 'Xスレッド',
    subtitle: '3〜5連投で論理展開',
    active: true,
    baseWeight: 1.1,
    question: '因果や構造を、3〜5つの流れに分けるなら？',
    ignitionWords: ['構造', '因果', '連投'],
  },
  {
    id: 'm-threads',
    deck: 'medium',
    title: 'Threads投稿',
    subtitle: '会話・共感から広げる',
    active: true,
    baseWeight: 1.1,
    question: '知識より会話から入るなら、最初の一文は何になる？',
    ignitionWords: ['会話', '共感', '問い'],
  },
  {
    id: 'm-instagram-carousel',
    deck: 'medium',
    title: 'Instagramカルーセル',
    subtitle: '保存される図解・教育投稿',
    active: true,
    baseWeight: 1,
    question: '体験→気づき→構造→行動を何枚で見せる？',
    ignitionWords: ['保存', '図解', '教育'],
  },
  {
    id: 'm-short-video',
    deck: 'medium',
    title: 'Reel / TikTok',
    subtitle: '短尺動画で身体感覚まで伝える',
    active: true,
    baseWeight: 1.2,
    question: '映像だから伝わる身体感覚は何か？',
    ignitionWords: ['身体性', '動き', '短尺'],
  },
  {
    id: 'm-note-article',
    deck: 'medium',
    title: 'note記事',
    subtitle: '物語と体系で深掘りする',
    active: true,
    baseWeight: 0.9,
    question: '一次体験から始めて、どんな普遍構造へつなげる？',
    ignitionWords: ['一次体験', '物語', '体系化'],
  },
  {
    id: 'm-line-delivery',
    deck: 'medium',
    title: 'LINE配信',
    subtitle: '既存接点へ直接届ける',
    active: true,
    baseWeight: 1.2,
    question: '今つながっている人へ、今日1通だけ送るなら？',
    ignitionWords: ['直接', '近距離', '次の一歩'],
  },
  {
    id: 'm-web-lp',
    deck: 'medium',
    title: 'Web / LP',
    subtitle: '体験・商品導線へ変換する',
    active: true,
    baseWeight: 0.9,
    question: '読むだけでなく、次の体験へ進む導線にするなら？',
    ignitionWords: ['体験', '導線', 'CTA'],
  },
  {
    id: 'm-discovery-quest',
    deck: 'medium',
    title: 'Discovery Quest設計',
    subtitle: '7日 / 14日プログラム素材へ変換',
    active: true,
    baseWeight: 0.9,
    question: 'このテーマを、読む知識ではなく1つのQuestにするなら？',
    ignitionWords: ['Quest', '実践', '変化'],
  },
  {
    id: 'm-drive-asset',
    deck: 'medium',
    title: 'Drive知識資産化',
    subtitle: '正本・教材・再利用知へ統合',
    active: true,
    baseWeight: 1,
    question: '今日の知識を、未来の自分やAIが再利用できる形にするなら？',
    ignitionWords: ['正本', '統合', '再利用'],
  },
];

export function getActiveHarnessCards(deck: HarnessDeck) {
  return HARNESS_CARDS.filter((card) => card.deck === deck && card.active);
}

function firstActive(deck: HarnessDeck) {
  const card = getActiveHarnessCards(deck)[0];
  if (!card) throw new Error(`No active Daily Harness card for deck: ${deck}`);
  return card;
}

export const PROTOTYPE_SELECTION: HarnessSelection = {
  vision: firstActive('vision'),
  theme: firstActive('theme'),
  medium: firstActive('medium'),
};
