export type DailyQuizCategory = 'body' | 'mind' | 'recovery' | 'decision';
export type DailyQuizBasis = 'evidence' | 'ace';

export type DailyQuiz = {
  id: string;
  category: DailyQuizCategory;
  question: string;
  choices: { id: string; text: string }[];
  correctChoiceId: string;
  explanation: string;
  action: string;
  xp: number;
  basis: DailyQuizBasis;
  sourceLabel: string;
};

// Evidence-based items are grounded in public-health guidance.
// ACE items are explicitly labeled as ACE principles/experience-based coaching rules.
export const DAILY_QUIZZES: DailyQuiz[] = [
  {
    id: 'body-01',
    category: 'body',
    question: '健康づくりのため、運動不足の人が最初に取る行動として最も適切なのは？',
    choices: [
      { id: 'A', text: 'いきなり高強度運動を毎日する' },
      { id: 'B', text: '少量の活動から始めて徐々に増やす' },
      { id: 'C', text: '週末だけ限界まで運動する' },
      { id: 'D', text: '150分できないなら何もしない' },
    ],
    correctChoiceId: 'B',
    explanation: '公的ガイドラインは「少しでも身体活動をする方が、まったくしないより良い」とし、少量から徐々に増やすことを勧めています。',
    action: '今日は10分だけ歩く。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO/CDC Physical Activity Guidelines',
  },
  {
    id: 'body-02',
    category: 'body',
    question: '成人の健康づくりで推奨される中強度の有酸素活動の目安は、週あたりどれくらい？',
    choices: [
      { id: 'A', text: '30分' },
      { id: 'B', text: '60分' },
      { id: 'C', text: '150分以上' },
      { id: 'D', text: '600分以上' },
    ],
    correctChoiceId: 'C',
    explanation: 'CDCなどのガイドラインでは、成人は週150分以上の中強度有酸素活動が基本目安です。',
    action: '今週の歩行・運動時間をざっくり合計する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'CDC Adult Activity Guidelines',
  },
  {
    id: 'body-03',
    category: 'body',
    question: '成人の筋力トレーニングは、健康づくりの目安として週何日以上が推奨される？',
    choices: [
      { id: 'A', text: '週1日' },
      { id: 'B', text: '週2日' },
      { id: 'C', text: '週5日' },
      { id: 'D', text: '毎日必須' },
    ],
    correctChoiceId: 'B',
    explanation: '成人は主要な筋群を使う筋力トレーニングを週2日以上行うことが推奨されています。',
    action: '今週の筋トレ日を2日だけ先に決める。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'CDC Adult Activity Guidelines',
  },
  {
    id: 'body-04',
    category: 'body',
    question: '座っている時間が長い日に、健康のため最も望ましい考え方は？',
    choices: [
      { id: 'A', text: '運動できない日は座り続けても同じ' },
      { id: 'B', text: '軽い活動でも座位時間を置き換える' },
      { id: 'C', text: '夜に1回立てば十分' },
      { id: 'D', text: '週末にまとめて動けば平日は関係ない' },
    ],
    correctChoiceId: 'B',
    explanation: 'WHOは、座位時間を減らし、軽い強度を含む身体活動に置き換えることにも健康上の利益があるとしています。',
    action: '次の1時間で一度立って2〜3分動く。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO Sedentary Behaviour Guidelines',
  },
  {
    id: 'body-05',
    category: 'body',
    question: '身体活動の効果として、ガイドラインで支持されているものは？',
    choices: [
      { id: 'A', text: '睡眠や気分の改善に役立つ可能性がある' },
      { id: 'B', text: '睡眠が不要になる' },
      { id: 'C', text: 'ストレスが完全になくなる' },
      { id: 'D', text: '病気を必ず防げる' },
    ],
    correctChoiceId: 'A',
    explanation: '身体活動は睡眠・気分・メンタルヘルスなどに良い影響が期待されますが、万能ではありません。',
    action: '5分だけ身体を動かした後の気分を10点満点で記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NIH/WHO Physical Activity',
  },
  {
    id: 'body-06',
    category: 'body',
    question: '運動習慣がほぼない人が活動量を増やすとき、より安全な進め方は？',
    choices: [
      { id: 'A', text: '頻度・強度・時間を一気に最大化する' },
      { id: 'B', text: '少量から段階的に増やす' },
      { id: 'C', text: '痛みが出ても続ける' },
      { id: 'D', text: '準備せず高強度だけ行う' },
    ],
    correctChoiceId: 'B',
    explanation: '身体活動は少量から始め、頻度・強度・時間を徐々に増やすことが推奨されています。',
    action: '今の運動量に“少しだけ”足せる行動を1つ決める。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO Physical Activity Guidelines',
  },
  {
    id: 'body-07',
    category: 'body',
    question: '健康づくりの「身体活動」に含まれるものは？',
    choices: [
      { id: 'A', text: 'スポーツだけ' },
      { id: 'B', text: 'ジムでの運動だけ' },
      { id: 'C', text: '移動・家事・仕事・運動など幅広い動き' },
      { id: 'D', text: '心拍数が高い運動だけ' },
    ],
    correctChoiceId: 'C',
    explanation: '身体活動には、運動・スポーツだけでなく、移動、仕事、家事などの身体を動かす活動も含まれます。',
    action: '今日は「運動以外の活動」を1つ増やす。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO Physical Activity Guidelines',
  },
  {
    id: 'body-08',
    category: 'body',
    question: '週150分の中強度運動が難しい場合の考え方として適切なのは？',
    choices: [
      { id: 'A', text: '達成できないなら意味がない' },
      { id: 'B', text: '少量でも健康上の利益は期待できる' },
      { id: 'C', text: '必ず一度に150分行う' },
      { id: 'D', text: '筋トレだけなら座位時間は無関係' },
    ],
    correctChoiceId: 'B',
    explanation: 'ガイドラインは、推奨量に届かなくても、身体活動を増やすこと自体に利益があるとしています。',
    action: '「ゼロか100か」をやめて、今日の最低ラインを5分にする。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO/CDC Physical Activity Guidelines',
  },
  {
    id: 'body-09',
    category: 'body',
    question: '週75分程度が目安になるのは、主にどの活動？',
    choices: [
      { id: 'A', text: '高強度の有酸素活動' },
      { id: 'B', text: '座位' },
      { id: 'C', text: '睡眠' },
      { id: 'D', text: 'ストレッチだけ' },
    ],
    correctChoiceId: 'A',
    explanation: '成人では週150分の中強度、または週75分の高強度有酸素活動、あるいはその組み合わせが目安です。',
    action: '自分の運動を「軽・中・高」のどれかに分類してみる。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'CDC Adult Activity Guidelines',
  },
  {
    id: 'body-10',
    category: 'body',
    question: '筋力トレーニングでガイドラインが重視しているのは？',
    choices: [
      { id: 'A', text: '腕だけを鍛える' },
      { id: 'B', text: '主要な筋群を幅広く使う' },
      { id: 'C', text: '毎回限界まで追い込む' },
      { id: 'D', text: '器具を必ず使う' },
    ],
    correctChoiceId: 'B',
    explanation: '推奨では脚・臀部・背中・腹部・胸・肩・腕など、主要な筋群を含めることが示されています。',
    action: '自分の筋トレで抜けている部位がないか確認する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'CDC Adult Activity Guidelines',
  },
  {
    id: 'body-11',
    category: 'body',
    question: '健康のための運動で最も大切な原則に近いのは？',
    choices: [
      { id: 'A', text: '一度の完璧さ' },
      { id: 'B', text: '継続できる量を積み重ねる' },
      { id: 'C', text: '常に最大強度' },
      { id: 'D', text: '疲れていても同量を義務化する' },
    ],
    correctChoiceId: 'B',
    explanation: '公的ガイドラインは、少量から始めて徐々に増やし、定期的に身体活動を行うことを重視しています。',
    action: '明日もできる強度で終える。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO/NIH Physical Activity',
  },
  {
    id: 'body-12',
    category: 'body',
    question: '身体活動とメンタル面の関係として適切なのは？',
    choices: [
      { id: 'A', text: '身体活動はメンタルヘルスと無関係' },
      { id: 'B', text: '身体活動は不安・抑うつ症状の軽減と関連する' },
      { id: 'C', text: '運動すれば全ての精神疾患が治る' },
      { id: 'D', text: '高強度運動だけに効果がある' },
    ],
    correctChoiceId: 'B',
    explanation: 'WHOは身体活動が不安・抑うつ症状の軽減など、メンタルヘルス上の利益と関連するとしています。治療の代替を意味するものではありません。',
    action: '気分が重い日は「3分歩く」を選択肢に入れる。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO Physical Activity Guidelines',
  },
  {
    id: 'body-13',
    category: 'body',
    question: '運動量を増やしている途中で新しい症状が出た場合、最も適切なのは？',
    choices: [
      { id: 'A', text: '無視して強度を上げる' },
      { id: 'B', text: '症状に応じて医療専門家へ相談する' },
      { id: 'C', text: '必ず運動を永久にやめる' },
      { id: 'D', text: 'SNSの体験談だけで判断する' },
    ],
    correctChoiceId: 'B',
    explanation: '活動量を増やす際に新たな症状が出た場合は、必要に応じて医療専門家へ相談することが勧められています。',
    action: '違和感を「根性」で片づけず、場所・強さ・経過を記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO Physical Activity Guidelines',
  },
  {
    id: 'body-14',
    category: 'body',
    question: '「今日は30分運動する時間がない」ときのACE的な最適解は？',
    choices: [
      { id: 'A', text: '今日は完全にゼロにする' },
      { id: 'B', text: '5〜10分でも動く' },
      { id: 'C', text: '明日2時間やって帳尻を合わせる' },
      { id: 'D', text: '罪悪感だけ持つ' },
    ],
    correctChoiceId: 'B',
    explanation: '健康上は短い活動でもゼロより有益です。ACEでは完璧さより「行動を途切れさせない」ことを重視します。',
    action: '今すぐ5分だけ歩くか動く。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'CDC/WHO + ACE principle',
  },
  {
    id: 'mind-01',
    category: 'mind',
    question: 'ストレス反応が起きたとき、身体で起こりやすい変化は？',
    choices: [
      { id: 'A', text: '心拍や呼吸が上がる' },
      { id: 'B', text: '必ず眠くなる' },
      { id: 'C', text: '必ず体温が下がる' },
      { id: 'D', text: '筋肉の緊張が必ず消える' },
    ],
    correctChoiceId: 'A',
    explanation: 'ストレス時の闘争・逃走反応では、心拍や呼吸が上がり、筋肉が緊張するなどの変化が起こります。',
    action: '緊張したら「呼吸・肩・顎」の3点を観察する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Stress',
  },
  {
    id: 'mind-02',
    category: 'mind',
    question: 'リラクセーション反応の特徴として最も近いものは？',
    choices: [
      { id: 'A', text: '呼吸や心拍が落ち着く方向に向かう' },
      { id: 'B', text: '心拍が必ず最大になる' },
      { id: 'C', text: '注意が必ず散漫になる' },
      { id: 'D', text: '睡眠が不要になる' },
    ],
    correctChoiceId: 'A',
    explanation: 'リラクセーション反応は、ストレス反応とは反対方向に、呼吸・心拍などが落ち着く状態として説明されています。',
    action: '1分だけ、ゆっくりした呼吸を試す。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Relaxation Techniques',
  },
  {
    id: 'mind-03',
    category: 'mind',
    question: 'ストレス対処として研究されている呼吸法に最も近いものは？',
    choices: [
      { id: 'A', text: 'ゆっくりした深い呼吸' },
      { id: 'B', text: '息をできるだけ長く止め続ける' },
      { id: 'C', text: '常に速く浅く呼吸する' },
      { id: 'D', text: '呼吸を意識しないことを義務化する' },
    ],
    correctChoiceId: 'A',
    explanation: 'ゆっくりした深い呼吸・横隔膜呼吸は、ストレス軽減を助ける可能性が研究されています。',
    action: '1分間だけ、無理のないゆっくりした呼吸をする。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Relaxation Techniques',
  },
  {
    id: 'mind-04',
    category: 'mind',
    question: '漸進的筋弛緩法（PMR）の基本は？',
    choices: [
      { id: 'A', text: '筋肉を順に緊張させてからゆるめる' },
      { id: 'B', text: 'ずっと全身に力を入れ続ける' },
      { id: 'C', text: '目を開けたまま走る' },
      { id: 'D', text: '呼吸を止める' },
    ],
    correctChoiceId: 'A',
    explanation: '漸進的筋弛緩法は、筋肉を順に緊張させ、その後ゆるめることで身体の緊張を自覚しやすくする方法です。',
    action: '肩を3秒すくめて、力を抜いた差を感じる。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Relaxation Techniques',
  },
  {
    id: 'mind-05',
    category: 'mind',
    question: 'ガイドイメージ（guided imagery）の説明として近いのは？',
    choices: [
      { id: 'A', text: '落ち着きと結びつく場面を心に描く' },
      { id: 'B', text: '難しい暗算を続ける' },
      { id: 'C', text: '筋肉を最大収縮させ続ける' },
      { id: 'D', text: '睡眠時間を削る' },
    ],
    correctChoiceId: 'A',
    explanation: 'ガイドイメージは、落ち着きと結びつく場面や出来事をイメージし、リラクセーションを促す方法です。',
    action: '自分が落ち着く場所を10秒だけ具体的に思い浮かべる。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Relaxation Techniques',
  },
  {
    id: 'mind-06',
    category: 'mind',
    question: '長期的なストレスについて適切なのは？',
    choices: [
      { id: 'A', text: '健康に影響することがある' },
      { id: 'B', text: '身体には一切影響しない' },
      { id: 'C', text: '必ず能力を高める' },
      { id: 'D', text: '睡眠とは無関係' },
    ],
    correctChoiceId: 'A',
    explanation: '慢性的なストレスは、睡眠や頭痛、消化器症状などを含む健康問題に関係することがあります。',
    action: '最近のストレス源を1つだけ言語化する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Stress',
  },
  {
    id: 'mind-07',
    category: 'mind',
    question: 'リラクセーション技法について最も適切な理解は？',
    choices: [
      { id: 'A', text: '必要な医療の代わりに使うもの' },
      { id: 'B', text: 'セルフケアの一部として使えるが、医療の代替とは限らない' },
      { id: 'C', text: 'どんな病気も治せる' },
      { id: 'D', text: '効果は必ず即時で同じ' },
    ],
    correctChoiceId: 'B',
    explanation: 'リラクセーション技法はセルフケアとして使えますが、必要な医療の代わりにしたり受診を遅らせたりすべきではありません。',
    action: '「セルフケアで扱う部分／専門家に相談する部分」を分ける。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Relaxation Techniques',
  },
  {
    id: 'mind-08',
    category: 'mind',
    question: '大事な場面で緊張した。ACEで最も避けたい反応は？',
    choices: [
      { id: 'A', text: '緊張を無理に消そうと格闘する' },
      { id: 'B', text: '呼吸を整える' },
      { id: 'C', text: '今やる動作へ注意を戻す' },
      { id: 'D', text: '緊張している事実を認識する' },
    ],
    correctChoiceId: 'A',
    explanation: 'ACEでは感情そのものを敵にせず、状態を認識し、身体を整え、次の動作へ注意を戻します。',
    action: '「緊張を消す」ではなく「緊張したまま1つ動く」。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE performance principle',
  },
  {
    id: 'mind-09',
    category: 'mind',
    question: '頭の中が混乱しているとき、ACEで最初に行うことは？',
    choices: [
      { id: 'A', text: '問題を全部同時に解決する' },
      { id: 'B', text: '今コントロールできる1つに絞る' },
      { id: 'C', text: '自分を責める' },
      { id: 'D', text: '情報をさらに大量に足す' },
    ],
    correctChoiceId: 'B',
    explanation: '混乱時は処理対象を減らし、次の一手を具体化する方が行動に移しやすくなります。ACEでは「一点に戻る」を重視します。',
    action: '今やることを1つだけ10文字以内で書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE focus principle',
  },
  {
    id: 'mind-10',
    category: 'mind',
    question: '感情が強く動いたとき、ACEの基本姿勢に最も近いのは？',
    choices: [
      { id: 'A', text: '感情＝自分そのものと決める' },
      { id: 'B', text: '感情を観察し、行動は別に選ぶ' },
      { id: 'C', text: '感情を完全に禁止する' },
      { id: 'D', text: '反射的に行動する' },
    ],
    correctChoiceId: 'B',
    explanation: 'ACEでは「感情があること」と「その感情のまま行動すること」を分けます。',
    action: '今の感情を一語で名づけ、その後に取る行動を別に決める。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE self-regulation principle',
  },
  {
    id: 'mind-11',
    category: 'mind',
    question: 'セルフチェックで「事実」と「解釈」を分ける目的は？',
    choices: [
      { id: 'A', text: '現実を無視するため' },
      { id: 'B', text: '自分の思い込みを事実扱いしないため' },
      { id: 'C', text: '感情をなくすため' },
      { id: 'D', text: '判断を他人に任せるため' },
    ],
    correctChoiceId: 'B',
    explanation: '観察できる事実と、自分が付けた意味・解釈を分けると、選択肢を見直しやすくなります。',
    action: '悩みを「事実／解釈」の2行に分けて書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE cognition principle',
  },
  {
    id: 'mind-12',
    category: 'mind',
    question: 'ミスをした直後、次のプレーに戻るためのACE的な問いは？',
    choices: [
      { id: 'A', text: 'なぜ自分はダメなのか？' },
      { id: 'B', text: '今この瞬間にできる1動作は何か？' },
      { id: 'C', text: '誰のせいか？' },
      { id: 'D', text: '過去を完全に消せるか？' },
    ],
    correctChoiceId: 'B',
    explanation: '次の出力を変えられるのは、現在の注意と行動です。ACEではミス後に「次の一動作」へ戻します。',
    action: '過去の失敗を1つ思い出し「次の一手」だけ言葉にする。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE reset principle',
  },
  {
    id: 'mind-13',
    category: 'mind',
    question: '「やる気が出たら始める」が続かないときのACE的な修正は？',
    choices: [
      { id: 'A', text: 'やる気を待ち続ける' },
      { id: 'B', text: '開始条件を小さく具体化する' },
      { id: 'C', text: '目標をさらに抽象的にする' },
      { id: 'D', text: '失敗した自分を責める' },
    ],
    correctChoiceId: 'B',
    explanation: '行動の入口を小さくすると、感情状態に依存せず開始しやすくなります。',
    action: 'やることを「2分で始められる形」に縮める。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE action principle',
  },
  {
    id: 'mind-14',
    category: 'mind',
    question: '心身を整える技法で最も重要な考え方は？',
    choices: [
      { id: 'A', text: '一度で完璧に効かせる' },
      { id: 'B', text: '自分に合う方法を安全に繰り返し試す' },
      { id: 'C', text: '不調があっても専門家に相談しない' },
      { id: 'D', text: '他人と同じ反応を必須にする' },
    ],
    correctChoiceId: 'B',
    explanation: 'リラクセーション技法の反応には個人差があります。ACEでは安全性を守りながら、自分の反応を観察して再現性を高めます。',
    action: '今日1つ試し、前後の感覚を10点満点で記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH + ACE practice',
  },
  {
    id: 'recovery-01',
    category: 'recovery',
    question: '成人の一般的な睡眠時間の目安として最も近いのは？',
    choices: [
      { id: 'A', text: '3〜4時間' },
      { id: 'B', text: '5〜6時間' },
      { id: 'C', text: '7〜9時間' },
      { id: 'D', text: '12〜14時間' },
    ],
    correctChoiceId: 'C',
    explanation: 'NHLBIは成人の一般的な睡眠時間の目安を7〜9時間としています。個人差や状況による違いはあります。',
    action: '昨夜の睡眠時間を記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI How Much Sleep Is Enough',
  },
  {
    id: 'recovery-02',
    category: 'recovery',
    question: '睡眠不足で影響を受けやすいものは？',
    choices: [
      { id: 'A', text: '判断や注意' },
      { id: 'B', text: '髪の色' },
      { id: 'C', text: '利き手' },
      { id: 'D', text: '血液型' },
    ],
    correctChoiceId: 'A',
    explanation: '睡眠不足は注意・判断に影響し、リスクを過小評価したり報酬を過大評価したりする可能性があります。',
    action: '寝不足の日は大きな判断を急がない。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI Circadian Rhythm Disorders',
  },
  {
    id: 'recovery-03',
    category: 'recovery',
    question: '睡眠習慣を整える方法として推奨されているものは？',
    choices: [
      { id: 'A', text: '毎日大きく就寝時刻を変える' },
      { id: 'B', text: 'なるべく一貫した睡眠スケジュールを保つ' },
      { id: 'C', text: '寝る直前まで強い光を浴び続ける' },
      { id: 'D', text: '睡眠時間を毎日削る' },
    ],
    correctChoiceId: 'B',
    explanation: '一貫した睡眠スケジュールは、一般的な睡眠習慣の改善策として推奨されています。',
    action: '今夜の就寝目安を先に決める。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Sleep Habits',
  },
  {
    id: 'recovery-04',
    category: 'recovery',
    question: '寝室環境として一般的に勧められるものは？',
    choices: [
      { id: 'A', text: '静か・暗い・涼しい' },
      { id: 'B', text: '明るく騒がしい' },
      { id: 'C', text: '常にテレビを最大音量' },
      { id: 'D', text: '強い照明をつけっぱなし' },
    ],
    correctChoiceId: 'A',
    explanation: '睡眠習慣の一部として、静かで暗く、涼しい寝室環境が勧められています。',
    action: '今夜、寝室の光を1段階減らす。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Sleep Habits',
  },
  {
    id: 'recovery-05',
    category: 'recovery',
    question: '寝る直前の強い人工光について、睡眠習慣として一般的に勧められるのは？',
    choices: [
      { id: 'A', text: 'できるだけ増やす' },
      { id: 'B', text: '近い時間帯は避ける' },
      { id: 'C', text: '一晩中浴びる' },
      { id: 'D', text: '睡眠とは無関係と決める' },
    ],
    correctChoiceId: 'B',
    explanation: 'テレビ・PC・スマホなどの明るい人工光を就寝直前に避けることは、一般的な睡眠習慣として推奨されています。',
    action: '就寝30分前だけ画面から離れる。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Sleep Habits',
  },
  {
    id: 'recovery-06',
    category: 'recovery',
    question: '睡眠不足が何日も続くときの「睡眠負債」とは？',
    choices: [
      { id: 'A', text: '失った睡眠が積み重なる考え方' },
      { id: 'B', text: '昼寝を禁止する制度' },
      { id: 'C', text: '睡眠をお金に換算する方法' },
      { id: 'D', text: '睡眠が不要になる現象' },
    ],
    correctChoiceId: 'A',
    explanation: '必要な睡眠より短い状態が続くと、失った睡眠が積み重なることを睡眠負債と呼びます。',
    action: '今週、普段より短かった睡眠をざっくり振り返る。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI Sleep Deprivation',
  },
  {
    id: 'recovery-07',
    category: 'recovery',
    question: '9時間を超えて眠ることについて最も適切なのは？',
    choices: [
      { id: 'A', text: '誰にとっても必ず有害' },
      { id: 'B', text: '若年成人・睡眠不足からの回復・病気の時などには役立つことがある' },
      { id: 'C', text: '全員が毎日12時間必要' },
      { id: 'D', text: '睡眠時間に個人差はない' },
    ],
    correctChoiceId: 'B',
    explanation: 'NHLBIは9時間超の睡眠が必ずしも有害とは限らず、若年成人や睡眠不足からの回復時、病気の時などに役立つ場合があるとしています。',
    action: '時間だけでなく「起床時の回復感」も記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI How Much Sleep Is Enough',
  },
  {
    id: 'recovery-08',
    category: 'recovery',
    question: '睡眠の健康を考えるとき、時間以外に重要なのは？',
    choices: [
      { id: 'A', text: '睡眠の質' },
      { id: 'B', text: '枕のブランドだけ' },
      { id: 'C', text: '寝室の壁紙だけ' },
      { id: 'D', text: '夢の回数だけ' },
    ],
    correctChoiceId: 'A',
    explanation: '睡眠は時間だけでなく、途切れず十分に休めるなど質も重要です。',
    action: '「時間／途中覚醒／起床時の感覚」の3つを記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI Sleep Health',
  },
  {
    id: 'recovery-09',
    category: 'recovery',
    question: '就寝前のリラクセーションについて適切なのは？',
    choices: [
      { id: 'A', text: '睡眠習慣の一部として使える' },
      { id: 'B', text: '不眠症の治療を必ず置き換える' },
      { id: 'C', text: '全員に同じ方法が必ず効く' },
      { id: 'D', text: '一切研究されていない' },
    ],
    correctChoiceId: 'A',
    explanation: 'リラクセーション技法は、就寝前の睡眠習慣の一部として使われることがあります。一方で不眠症ではCBT-Iなど標準的治療が重要です。',
    action: '就寝前に1分だけ呼吸か筋弛緩を試す。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NCCIH Sleep Disorders',
  },
  {
    id: 'recovery-10',
    category: 'recovery',
    question: '回復を考えるときのACE的な優先順位として最も近いのは？',
    choices: [
      { id: 'A', text: '感覚を無視して予定を守る' },
      { id: 'B', text: '睡眠・身体感覚・活動量を観察して調整する' },
      { id: 'C', text: '毎日同じ強度を義務化する' },
      { id: 'D', text: '疲労を根性だけで処理する' },
    ],
    correctChoiceId: 'B',
    explanation: 'ACEでは回復もトレーニングの一部として扱い、睡眠・身体感覚・活動量を観察して次の負荷を調整します。',
    action: '今日の回復度を10点満点でつける。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE recovery principle',
  },
  {
    id: 'recovery-11',
    category: 'recovery',
    question: '「疲れている＝必ず完全休養」についてACEではどう考える？',
    choices: [
      { id: 'A', text: '必ず寝たきりにする' },
      { id: 'B', text: '状態を見て休養・軽い活動・通常活動を選び分ける' },
      { id: 'C', text: '疲労は全部気のせい' },
      { id: 'D', text: '痛みがあっても最大強度' },
    ],
    correctChoiceId: 'B',
    explanation: '疲労の原因や程度は一つではありません。ACEでは状態を観察し、必要なら休養、問題なければ軽い活動などを選びます。',
    action: '疲労を「身体・睡眠・心理・活動量」の4項目で見てみる。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE recovery principle',
  },
  {
    id: 'recovery-12',
    category: 'recovery',
    question: '寝不足の日に重要な意思決定をするときのACE的な対応は？',
    choices: [
      { id: 'A', text: '普段より大胆に決める' },
      { id: 'B', text: '判断力低下の可能性を考え、重要判断は慎重にする' },
      { id: 'C', text: '睡眠不足は判断に影響しないと決める' },
      { id: 'D', text: '直感だけで即決する' },
    ],
    correctChoiceId: 'B',
    explanation: '睡眠不足は判断に影響する可能性があるため、重要な判断ではその状態自体を条件として考慮します。',
    action: '今日寝不足なら、大きな決断を「一晩置けるか」確認する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI Circadian Rhythm Disorders',
  },
  {
    id: 'recovery-13',
    category: 'recovery',
    question: '睡眠改善で最初に記録すると役立ちやすい組み合わせは？',
    choices: [
      { id: 'A', text: '就寝時刻・起床時刻・起床時の感覚' },
      { id: 'B', text: '夢の色だけ' },
      { id: 'C', text: '寝具の値段だけ' },
      { id: 'D', text: 'SNS閲覧数だけ' },
    ],
    correctChoiceId: 'A',
    explanation: '睡眠日誌では睡眠時間や日中の状態などを記録し、パターンを見ることが役立ちます。',
    action: '今夜から3項目だけ記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'NHLBI Sleep Diary / ACE practice',
  },
  {
    id: 'recovery-14',
    category: 'recovery',
    question: '回復を良くするため「全部一度に変える」よりACEが勧めるのは？',
    choices: [
      { id: 'A', text: '一つ変えて反応を見る' },
      { id: 'B', text: '毎日10個ルールを追加する' },
      { id: 'C', text: '記録を一切しない' },
      { id: 'D', text: '他人の習慣をそのままコピーする' },
    ],
    correctChoiceId: 'A',
    explanation: '一度に一つ変えると、自分に何が影響したかを観察しやすくなります。ACEでは再現性を作るために小さく試します。',
    action: '今夜の改善は1つだけ選ぶ。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE experimentation principle',
  },
  {
    id: 'decision-01',
    category: 'decision',
    question: '試合や仕事でミスをした直後、次の結果を最も変えやすい対象は？',
    choices: [
      { id: 'A', text: 'すでに起きたミス' },
      { id: 'B', text: '次の一動作' },
      { id: 'C', text: '観客の反応' },
      { id: 'D', text: '過去の判定' },
    ],
    correctChoiceId: 'B',
    explanation: '過去の出来事は変えられませんが、現在の注意と次の行動は選び直せます。',
    action: '「次にやる1動作」を声に出す。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE controllables principle',
  },
  {
    id: 'decision-02',
    category: 'decision',
    question: '情報が多すぎて決められないとき、ACEの第一手は？',
    choices: [
      { id: 'A', text: 'さらに情報を無制限に集める' },
      { id: 'B', text: '判断基準を1〜3個に絞る' },
      { id: 'C', text: 'ランダムに決める' },
      { id: 'D', text: '永遠に保留する' },
    ],
    correctChoiceId: 'B',
    explanation: '選択肢より先に判断基準を定めると、意思決定が整理されます。',
    action: '今回の判断基準を3つ以内で書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE decision principle',
  },
  {
    id: 'decision-03',
    category: 'decision',
    question: '「なんとなく不安だからやめる」前に確認したいものは？',
    choices: [
      { id: 'A', text: '不安の中身と実際のリスク' },
      { id: 'B', text: 'SNSの多数派だけ' },
      { id: 'C', text: '最悪の想像だけ' },
      { id: 'D', text: '他人の感情だけ' },
    ],
    correctChoiceId: 'A',
    explanation: '感情は重要な情報ですが、事実・確率・影響と分けて見ることで判断の精度を上げられます。',
    action: '不安を「事実／想像／対策」に3分割する。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE risk principle',
  },
  {
    id: 'decision-04',
    category: 'decision',
    question: '目標が「もっと健康になる」だけで動けない。最初の修正は？',
    choices: [
      { id: 'A', text: 'さらに抽象化する' },
      { id: 'B', text: '今日できる観察可能な行動に変える' },
      { id: 'C', text: '期限を全部なくす' },
      { id: 'D', text: '気合を入れるだけ' },
    ],
    correctChoiceId: 'B',
    explanation: '抽象目標は方向を示しますが、実行には具体的な行動への翻訳が必要です。',
    action: '「今日10分歩く」のように1動作へ変換する。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE action design',
  },
  {
    id: 'decision-05',
    category: 'decision',
    question: '予定通りできなかった日の評価としてACEに近いのは？',
    choices: [
      { id: 'A', text: '自分は意志が弱いと決める' },
      { id: 'B', text: '設計のどこで詰まったかを見る' },
      { id: 'C', text: '全部やめる' },
      { id: 'D', text: '失敗を隠す' },
    ],
    correctChoiceId: 'B',
    explanation: '人格ではなく、時間・環境・難易度・開始条件など「設計」を見ると次の改善につながります。',
    action: '詰まった場所を1つだけ特定する。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE feedback principle',
  },
  {
    id: 'decision-06',
    category: 'decision',
    question: '習慣が3日で止まった。次の一手として最もACEらしいのは？',
    choices: [
      { id: 'A', text: '目標を倍にする' },
      { id: 'B', text: '再開ラインを小さくする' },
      { id: 'C', text: '自分を責め続ける' },
      { id: 'D', text: '完全に忘れる' },
    ],
    correctChoiceId: 'B',
    explanation: '継続が止まったときは、再開コストを下げる方が行動を戻しやすくなります。',
    action: '明日の最低ラインを「2分」にする。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE restart principle',
  },
  {
    id: 'decision-07',
    category: 'decision',
    question: '他人から厳しいフィードバックを受けた。最初に分けたいものは？',
    choices: [
      { id: 'A', text: '内容と感情反応' },
      { id: 'B', text: '相手の人格と自分の人格' },
      { id: 'C', text: '勝ち負けだけ' },
      { id: 'D', text: 'SNSの評価' },
    ],
    correctChoiceId: 'A',
    explanation: '感情反応と、利用できる情報を分けると、必要な部分だけ改善材料として扱えます。',
    action: 'フィードバックから「使える1点」だけ抜き出す。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE feedback principle',
  },
  {
    id: 'decision-08',
    category: 'decision',
    question: '大事な本番前ルーティンの目的としてACEに近いのは？',
    choices: [
      { id: 'A', text: '必ず緊張をゼロにする' },
      { id: 'B', text: '再現可能な注意と身体状態へ戻る' },
      { id: 'C', text: '毎回違うことをする' },
      { id: 'D', text: '結果を保証する' },
    ],
    correctChoiceId: 'B',
    explanation: 'ルーティンは結果を保証する魔法ではなく、自分が再現しやすい状態・注意へ戻るための手順です。',
    action: '本番前30秒の手順を3ステップで書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE performance routine',
  },
  {
    id: 'decision-09',
    category: 'decision',
    question: '予想外のトラブルが起きたとき、最初に整理する問いは？',
    choices: [
      { id: 'A', text: '誰が悪い？' },
      { id: 'B', text: '今コントロールできるものは何？' },
      { id: 'C', text: 'なぜ人生はこうなの？' },
      { id: 'D', text: '全部元通りにできる？' },
    ],
    correctChoiceId: 'B',
    explanation: 'コントロール可能な対象へ注意を戻すと、次の行動を作りやすくなります。',
    action: '紙に「変えられる／変えられない」を2列で書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE controllables principle',
  },
  {
    id: 'decision-10',
    category: 'decision',
    question: '新しい健康法を見つけた。試す前のACEチェックとして最も良いのは？',
    choices: [
      { id: 'A', text: '発信者の肩書だけで信じる' },
      { id: 'B', text: '根拠・利益相反・リスク・自分への適合を確認する' },
      { id: 'C', text: '反対意見を見ない' },
      { id: 'D', text: '一度に複数導入する' },
    ],
    correctChoiceId: 'B',
    explanation: 'ACEでは権威だけに依存せず、根拠・利益相反・リスク・自分への適合を確認してから小さく試します。',
    action: '最近気になる健康法を1つ、一次情報まで確認する。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE evidence principle',
  },
  {
    id: 'decision-11',
    category: 'decision',
    question: 'トレーニング中に普段と違う強い痛みが出た。最も安全寄りの判断は？',
    choices: [
      { id: 'A', text: '根性で続ける' },
      { id: 'B', text: '中止または負荷を下げ、状態を評価する' },
      { id: 'C', text: '痛いほど効いていると決める' },
      { id: 'D', text: 'SNS投稿を優先する' },
    ],
    correctChoiceId: 'B',
    explanation: '普段と違う強い痛みは無視せず、活動を中止・調整し、必要なら専門家に相談するのが安全です。',
    action: '「痛みの場所・強さ・きっかけ」を記録する。',
    xp: 10,
    basis: 'evidence',
    sourceLabel: 'WHO safety principle + ACE',
  },
  {
    id: 'decision-12',
    category: 'decision',
    question: '疲労している日に「いつも通りできない」と感じた。ACEの判断は？',
    choices: [
      { id: 'A', text: '自分の価値が下がったと考える' },
      { id: 'B', text: 'その日の状態に合わせて出力目標を調整する' },
      { id: 'C', text: '必ず最大強度' },
      { id: 'D', text: '何も観察しない' },
    ],
    correctChoiceId: 'B',
    explanation: 'パフォーマンスは状態によって変動します。ACEでは「今日の条件で再現できる最善」へ目標を調整します。',
    action: '今日の出力目標を100点ではなく「現状の8割」で決める。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE state-based performance',
  },
  {
    id: 'decision-13',
    category: 'decision',
    question: '新しい方法を試した結果が良かった。次にすることは？',
    choices: [
      { id: 'A', text: '1回で絶対に効くと断定する' },
      { id: 'B', text: '条件を記録して再現するか確かめる' },
      { id: 'C', text: '他の要因を全部無視する' },
      { id: 'D', text: '全員に同じ効果があると宣言する' },
    ],
    correctChoiceId: 'B',
    explanation: '一度の成功だけでは再現性は分かりません。条件を記録して繰り返し確かめることで、自分にとって使える知恵になります。',
    action: 'うまくいった理由の候補を3つ書く。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE experimentation principle',
  },
  {
    id: 'decision-14',
    category: 'decision',
    question: 'ACE QUESTの最終目的は？',
    choices: [
      { id: 'A', text: 'クイズの正答率だけを上げる' },
      { id: 'B', text: '知識を行動と身体化につなげる' },
      { id: 'C', text: '他人より点数を高くする' },
      { id: 'D', text: '問題文を暗記する' },
    ],
    correctChoiceId: 'B',
    explanation: 'ACE QUESTは「知る→気づく→選ぶ→やる→身体化する」を繰り返し、自分で調整できる力を育てるための設計です。',
    action: '今日のクイズから1つだけ実行する。',
    xp: 10,
    basis: 'ace',
    sourceLabel: 'ACE core principle',
  },
];

export function getDailyQuiz(date = new Date()): DailyQuiz {
  const start = Date.UTC(2026, 7, 19);
  const today = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  const dayIndex = Math.floor((today - start) / 86_400_000);
  const index = ((dayIndex % DAILY_QUIZZES.length) + DAILY_QUIZZES.length) % DAILY_QUIZZES.length;
  return DAILY_QUIZZES[index];
}

export function getQuizzesByCategory(category: DailyQuizCategory): DailyQuiz[] {
  return DAILY_QUIZZES.filter((quiz) => quiz.category === category);
}
