name = "ace-quest-board-dev"
compatibility_date = "2026-08-27"
workers_dev = true

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[env.production]
name = "ace-quest-board"
workers_dev = true

[[env.production.routes]]
pattern = "ace.sunlovesflow.com"
custom_domain = true
