'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { CATEGORY_COLORS, WANT_TO_SEED, type WantToSeed } from '@/lib/wantToSeed';
import { APP_ROUTES, WANT_TO_SHEET_URL } from '@/lib/appRoutes';

type Achievement = { id:string; wantId:string; date:string; withWho:string; place:string; satisfaction:number; repeat:number; note:string };
type LevelMap = Record<string, number>;
type ViewMode = 'cards' | 'table';
type EnrichedWant = WantToSeed & { theme:string; type:string; timing:string; logs:Achievement[]; count:number; avgSatisfaction:number|null; avgRepeat:number|null; myLevel?:number };

const ACHIEVEMENT_KEY='ace-want-achievements-v1';
const LEVEL_KEY='ace-want-levels-v1';

function todayLocal(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function avg(v:number[]){return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length*10)/10:null}
function stars(n:number){return '★'.repeat(n)+'☆'.repeat(Math.max(0,5-n))}
function inferTheme(item:WantToSeed){const s=`${item.title} ${item.action}`;if(/生ききる|自分の人生|自分に戻る|自己決定|Want to|直感|自分しかできない/.test(s))return'自己一致・自由';if(/睡眠|食事|健康|副交感|美容|口腔|脳機能|身体機能|回復/.test(s))return'回復・健康';if(/パートナー|家族|親子|安心|仲間|信頼|関係/.test(s))return'愛・つながり';if(/自然|BASE|平屋|二拠点|三拠点|土地|旅|温泉|日光|朝日|畑/.test(s))return'自然・暮らし';if(/身体|競技|セパタクロー|アスリート|挑戦/.test(s))return'挑戦・身体性';if(/研究|理解|解明|哲学|数秘|エニアグラム|一次資料|反証|分析|学習|仮説/.test(s))return'探究・理解';if(/AI|OS|自動化|体系化|知識|再利用|仕組み|メソッド|モデル|プロトコル/.test(s))return'知識化・仕組み化';if(/note|SNS|ブランド|発信|物語|検索|ストーリー|世界観|SEO/.test(s))return'表現・物語';if(/商品|売上|収益|事業|仕事|現金化|顧客/.test(s))return'価値提供・収益';if(/お金|資産|キャッシュフロー|防衛資金|資本|投資/.test(s))return'自由・資産';if(/ACE|教育|育てる|成長OS|ゴール設定|コミュニティ|実践者/.test(s))return'育成・自己決定';if(/次世代|残す|継承|世界一/.test(s))return'継承・レガシー';if(/地域|国づくり|日本|社会|循環|生産者/.test(s))return'循環・社会実装';return'統合・成長'}
function inferType(item:WantToSeed){const s=`${item.title} ${item.action}`;if(item.category==='家族・人間関係'&&/関係|パートナー|家族|親子|仲間|信頼|協力|話/.test(s))return'関係性';if(/研究|理解|解明|分析|学習|判断|読み解く|仮説|反証/.test(s))return'探究';if(/土地を持つ|資金を持つ|防衛資金|資格取得|実物資産|取得|購入/.test(s))return'獲得';if(/旅|温泉|体験|行く|見る|食べる/.test(s))return'体験';if(/仕組み|OS|体系|自動化|メソッド|プログラム|モデル|循環|自走|プロトコル/.test(s))return'仕組み';if(/作る|完成|確立|商品化|強くする|発展させる|増やす|育てる|教材化/.test(s))return'プロジェクト';if(/毎|定期的|続ける|日常化|習慣|保つ|積み上げる|ルーチン/.test(s))return'習慣';if(item.category==='地域・社会・未来')return'貢献';return'状態'}
function timingFor(type:string,item:WantToSeed){if(type==='体験')return/増やす|続ける|定期|毎|季節/.test(item.title)?'Ongoing':'One-shot';if(type==='獲得')return'One-shot';if(type==='プロジェクト'||type==='仕組み')return'Hybrid';return'Ongoing'}
function csvEscape(v:unknown){return `"${String(v??'').replaceAll('"','""')}"`}

export default function WantToPage(){
 const[query,setQuery]=useState('');const[category,setCategory]=useState('');const[source,setSource]=useState('');const[tier,setTier]=useState('');const[typeFilter,setTypeFilter]=useState('');const[pinOnly,setPinOnly]=useState(false);const[view,setView]=useState<ViewMode>('cards');const[selected,setSelected]=useState<EnrichedWant|null>(null);const[achieving,setAchieving]=useState<WantToSeed|null>(null);const[achievements,setAchievements]=useState<Achievement[]>([]);const[levels,setLevels]=useState<LevelMap>({});const[hydrated,setHydrated]=useState(false);const[handledLink,setHandledLink]=useState(false);
 useEffect(()=>{try{setAchievements(JSON.parse(localStorage.getItem(ACHIEVEMENT_KEY)||'[]'));setLevels(JSON.parse(localStorage.getItem(LEVEL_KEY)||'{}'))}catch{setAchievements([]);setLevels({})}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(ACHIEVEMENT_KEY,JSON.stringify(achievements))},[achievements,hydrated]);useEffect(()=>{if(hydrated)localStorage.setItem(LEVEL_KEY,JSON.stringify(levels))},[levels,hydrated]);
 const enriched=useMemo<EnrichedWant[]>(()=>WANT_TO_SEED.map(item=>{const theme=inferTheme(item),type=inferType(item),timing=timingFor(type,item),logs=achievements.filter(a=>a.wantId===item.id);return{...item,theme,type,timing,logs,count:logs.length,avgSatisfaction:avg(logs.map(a=>a.satisfaction)),avgRepeat:avg(logs.map(a=>a.repeat)),myLevel:levels[item.id]}}),[achievements,levels]);
 useEffect(()=>{if(handledLink||!hydrated)return;const requested=new URLSearchParams(window.location.search).get('q');if(requested){const id=requested.toUpperCase();setQuery(id);const found=enriched.find(x=>x.id===id);if(found)setSelected(found)}setHandledLink(true)},[enriched,handledLink,hydrated]);
 const categories=useMemo(()=>[...new Set(WANT_TO_SEED.map(x=>x.category))],[]);const types=useMemo(()=>[...new Set(enriched.map(x=>x.type))],[enriched]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return enriched.filter(i=>{const h=[i.id,i.category,i.title,i.source,i.tier,i.action,i.theme,i.type,i.timing,...i.prereq,...i.related].join(' ').toLowerCase();return(!q||h.includes(q))&&(!category||i.category===category)&&(!source||i.source===source)&&(!tier||i.tier===tier)&&(!typeFilter||i.type===typeFilter)&&(!pinOnly||i.pin===5)})},[enriched,query,category,source,tier,typeFilter,pinOnly]);
 function saveAchievement(payload:Omit<Achievement,'id'>){setAchievements(p=>[{...payload,id:`${Date.now()}-${Math.random().toString(36).slice(2)}`},...p]);setAchieving(null)}
 function exportLogs(){const header=['Log ID','達成日','親Want ID','達成したこと','誰と','場所・体験','満足度 0-5','またやりたい度 0-5','メモ'];const rows=achievements.map(a=>{const w=WANT_TO_SEED.find(x=>x.id===a.wantId);return[a.id,a.date,a.wantId,w?.title||'',a.withWho,a.place,a.satisfaction,a.repeat,a.note]});const csv='\uFEFF'+[header,...rows].map(r=>r.map(csvEscape).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`want-to-achievements-${todayLocal()}.csv`;link.click();URL.revokeObjectURL(url)}
 const reset=()=>{setQuery('');setCategory('');setSource('');setTier('');setTypeFilter('');setPinOnly(false)};
 return <div className="min-h-screen bg-[#f0eadc] text-[#1c211d] selection:bg-[#c8ab72]/35">
  <div className="pointer-events-none fixed inset-0 opacity-[0.28]" style={{backgroundImage:'repeating-linear-gradient(0deg,rgba(70,76,68,.035) 0,rgba(70,76,68,.035) 1px,transparent 1px,transparent 5px),repeating-linear-gradient(90deg,rgba(70,76,68,.02) 0,rgba(70,76,68,.02) 1px,transparent 1px,transparent 8px)'}}/>
  <main className="relative z-10 mx-auto max-w-[1500px] px-4 py-6 md:px-7">
   <section className="mb-5 flex flex-wrap items-end justify-between gap-4">
    <div className="flex min-w-0 items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full border border-[#9a8055]/35 font-serif text-sm text-[#806a46]">望</div><div><div className="text-[9px] font-bold tracking-[.22em] text-[#8f754d]">DIRECTION LAYER</div><h1 className="font-serif text-lg font-semibold tracking-wide">Want to Master</h1><p className="text-[9px] tracking-wide text-[#72786f]">願いを、方向として育てる。</p></div></div>
    <a href={WANT_TO_SHEET_URL} target="_blank" rel="noreferrer" className="rounded-full border border-[#9a8055]/20 px-3 py-2 text-[10px] font-semibold text-[#74613f] hover:border-[#9a8055]/40">Sheet ↗</a>
   </section>
   <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Want to" value={WANT_TO_SEED.length} note="現在のアプリSnapshot"/><Stat label="表示中" value={visible.length} note="検索・絞り込み"/><Stat label="中心ピン" value={WANT_TO_SEED.filter(x=>x.pin===5).length} note="★★★★★"/><Stat label="達成ログ" value={achievements.length} note={`${new Set(achievements.map(a=>a.wantId)).size}項目`}/><Stat label="現在地評価" value={Object.keys(levels).length} note="0〜5本人評価"/></section>
   <section className="mt-5 border border-[#9a8055]/15 bg-[#f7f2e8]/70 p-4 shadow-[0_22px_70px_rgba(60,52,38,.07)] backdrop-blur-sm"><div className="grid gap-3 lg:grid-cols-[2fr_repeat(4,1fr)]">
    <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="温泉、家族、ACE、健康、W038…" className="min-h-12 border border-[#9a8055]/20 bg-[#f8f4ea] px-4 font-serif text-sm outline-none placeholder:text-[#9a9b91] focus:border-[#9a8055]/45"/>
    <Select value={category} set={setCategory} empty="全ジャンル" values={categories}/><Select value={source} set={setSource} empty="全確度" values={['明示','AI推定','探索候補']}/><Select value={tier} set={setTier} empty="全階層" values={['前提','中間','上位']}/><Select value={typeFilter} set={setTypeFilter} empty="全Want to型" values={types}/>
   </div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><button onClick={()=>setPinOnly(x=>!x)} className={`rounded-full border px-3 py-2 text-[10px] font-bold ${pinOnly?'border-[#a7864e] bg-[#c8ab72]/25 text-[#6f552c]':'border-[#9a8055]/20 text-[#6c6f67]'}`}>★★★★★だけ</button><button onClick={reset} className="rounded-full border border-[#9a8055]/20 px-3 py-2 text-[10px] font-semibold text-[#6c6f67]">リセット</button></div><div className="flex rounded-full border border-[#9a8055]/20 p-1 text-[10px] font-bold"><button onClick={()=>setView('cards')} className={`rounded-full px-3 py-1.5 ${view==='cards'?'bg-[#1c211d] text-[#eee7d9]':''}`}>カード</button><button onClick={()=>setView('table')} className={`rounded-full px-3 py-1.5 ${view==='table'?'bg-[#1c211d] text-[#eee7d9]':''}`}>表</button></div></div></section>
   <div className="mt-3 flex items-center justify-between px-1 text-[9px] tracking-wide text-[#85877e]"><span>知 → 望 → 行</span><button onClick={exportLogs} disabled={!achievements.length} className="font-semibold text-[#78633f] disabled:opacity-30">達成ログCSV ↗</button></div>
   {view==='cards'?<section className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visible.map(item=><article key={item.id} className="group relative overflow-hidden border border-[#9a8055]/14 bg-[#f8f4ea]/92 p-5 shadow-[0_15px_50px_rgba(68,57,37,.055)] transition hover:-translate-y-0.5 hover:border-[#9a8055]/28 hover:shadow-[0_22px_65px_rgba(68,57,37,.09)]"><div className="absolute left-0 top-0 h-full w-[3px] opacity-80" style={{backgroundColor:CATEGORY_COLORS[item.category]}}/><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap gap-1.5 text-[9px] font-semibold"><span className="text-[#8c724a]">{item.id}</span><span className="text-[#777c74]">{item.category}</span><span className="text-[#9a9b91]">{item.source}</span></div><h2 className="mt-3 font-serif text-lg font-semibold leading-[1.65] text-[#252a25]">{item.title}</h2></div><div className="shrink-0 text-right"><div className="text-[10px] tracking-[-.08em] text-[#a68753]">{stars(item.pin)}</div><div className="mt-1 text-[9px] text-[#96988f]">{item.tier}</div></div></div><div className="mt-3 flex flex-wrap gap-1.5 text-[9px]"><Tag>{item.theme}</Tag><Tag>{item.type}</Tag><Tag>{item.timing}</Tag></div><p className="mt-4 line-clamp-2 font-serif text-[12px] leading-7 text-[#686d66]">{item.action}</p><div className="mt-4 grid grid-cols-3 border-y border-[#9a8055]/10 py-3 text-center"><Mini label="現在地" value={item.myLevel===undefined?'—':`${item.myLevel}/5`}/><Mini label="達成" value={`${item.count}回`}/><Mini label="満足" value={item.avgSatisfaction===null?'—':String(item.avgSatisfaction)}/></div><div className="mt-4 flex gap-2"><button onClick={()=>setSelected(item)} className="flex-1 border border-[#9a8055]/20 px-3 py-2.5 text-[11px] font-semibold text-[#5e655e] hover:bg-[#eee6d7]">詳しく見る</button><button onClick={()=>setAchieving(item)} className="flex-1 bg-[#1d241f] px-3 py-2.5 text-[11px] font-semibold text-[#e8dfcf] hover:bg-[#293129]">叶えた</button></div></article>)}</section>:<TableView items={visible} open={setSelected} achieve={setAchieving}/>} {!visible.length&&<div className="mt-16 text-center font-serif text-[#8b8d84]">該当するWant toがありません。</div>}
  </main>
  {selected&&<DetailModal item={selected} level={levels[selected.id]} onLevel={n=>setLevels(p=>({...p,[selected.id]:n}))} onAchieve={()=>{setSelected(null);setAchieving(selected)}} onClose={()=>setSelected(null)}/>} {achieving&&<AchievementModal item={achieving} onSave={saveAchievement} onClose={()=>setAchieving(null)}/>} </div>
}

function Select({value,set,empty,values}:{value:string;set:(v:string)=>void;empty:string;values:string[]}){return <select value={value} onChange={e=>set(e.target.value)} className="min-h-12 border border-[#9a8055]/20 bg-[#f8f4ea] px-3 text-[11px] text-[#5f655e] outline-none"><option value="">{empty}</option>{values.map(x=><option key={x}>{x}</option>)}</select>}
function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <div className="border border-[#9a8055]/13 bg-[#f8f4ea]/75 p-4"><div className="font-serif text-2xl font-semibold text-[#2b302b]">{value}</div><div className="mt-1 text-[10px] font-bold tracking-wide text-[#6f746d]">{label}</div><div className="mt-1 text-[9px] text-[#9a9b93]">{note}</div></div>}
function Mini({label,value}:{label:string;value:string}){return <div><div className="font-serif text-base font-semibold">{value}</div><div className="text-[9px] text-[#9b9b92]">{label}</div></div>}
function Tag({children}:{children:React.ReactNode}){return <span className="rounded-full border border-[#789581]/16 bg-[#789581]/[0.055] px-2 py-1 text-[#66756a]">{children}</span>}
function TableView({items,open,achieve}:{items:EnrichedWant[];open:(x:EnrichedWant)=>void;achieve:(x:WantToSeed)=>void}){return <section className="mt-4 overflow-x-auto border border-[#9a8055]/14 bg-[#f8f4ea]/90"><table className="w-full min-w-[1050px] border-collapse text-[11px]"><thead className="bg-[#e7dece]/70 text-left text-[#777b73]"><tr><th className="p-3">ID</th><th>ジャンル</th><th>Want to</th><th>テーマ</th><th>型</th><th>中心ピン</th><th>現在地</th><th>達成</th><th>操作</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t border-[#9a8055]/10"><td className="p-3 font-semibold text-[#8a7048]">{i.id}</td><td>{i.category}</td><td className="max-w-sm py-3 font-serif text-[12px] font-semibold">{i.title}</td><td>{i.theme}</td><td>{i.type}</td><td className="text-[#a68753]">{stars(i.pin)}</td><td>{i.myLevel===undefined?'—':`${i.myLevel}/5`}</td><td>{i.count}回</td><td><div className="flex gap-1"><button onClick={()=>open(i)} className="border border-[#9a8055]/20 px-2 py-1">詳細</button><button onClick={()=>achieve(i)} className="bg-[#1d241f] px-2 py-1 text-[#e8dfcf]">叶えた</button></div></td></tr>)}</tbody></table></section>}
function DetailModal({item,level,onLevel,onAchieve,onClose}:{item:EnrichedWant;level?:number;onLevel:(n:number)=>void;onAchieve:()=>void;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#090a08]/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" onMouseDown={onClose}><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto border border-[#c8ab72]/20 bg-[#f4eee1] p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] font-bold tracking-[.18em] text-[#9a8055]">{item.id} · {item.category}</div><h2 className="mt-3 font-serif text-2xl font-semibold leading-[1.55]">{item.title}</h2></div><button onClick={onClose} className="text-xl text-[#85887f]">×</button></div><div className="mt-3 flex flex-wrap gap-2 text-[9px]"><Tag>{item.theme}</Tag><Tag>{item.type}</Tag><Tag>{item.timing}</Tag><span className="text-[#a68753]">{stars(item.pin)}</span></div><section className="mt-6 border-y border-[#9a8055]/13 py-5"><div className="text-[9px] font-bold tracking-[.15em] text-[#8b8f87]">CLEAR / ACTION</div><p className="mt-2 font-serif text-[13px] leading-8 text-[#585f58]">{item.action}</p></section><section className="mt-5"><div className="text-[9px] font-bold tracking-[.15em] text-[#8b8f87]">現在地</div><div className="mt-3 flex gap-2">{[0,1,2,3,4,5].map(n=><button key={n} onClick={()=>onLevel(n)} className={`h-10 w-10 rounded-full border text-sm font-semibold ${level===n?'border-[#1d241f] bg-[#1d241f] text-[#eee6d8]':'border-[#9a8055]/25 text-[#687068]'}`}>{n}</button>)}</div><div className="mt-2 text-[9px] text-[#8d9088]">0 未着手 → 1 構想 → 2 試行 → 3 実行 → 4 定着 → 5 自走・展開</div></section><section className="mt-5 grid gap-3 sm:grid-cols-2"><Box label="前提" values={item.prereq}/><Box label="関連" values={item.related}/></section><section className="mt-5 border border-[#9a8055]/13 p-4"><div className="flex justify-between"><div className="text-[9px] font-bold tracking-[.15em] text-[#8b8f87]">ACHIEVEMENT</div><div className="font-serif text-sm font-semibold">{item.logs.length}回</div></div>{item.logs.slice(0,4).map(a=><div key={a.id} className="mt-3 border-t border-[#9a8055]/10 pt-3 text-[11px]"><div className="font-semibold">{a.date}{a.place?` · ${a.place}`:''}</div><div className="mt-1 text-[9px] text-[#858980]">{a.withWho||'同伴者未記録'} · 満足 {a.satisfaction}/5 · またやりたい {a.repeat}/5</div>{a.note&&<div className="mt-1 text-[10px] text-[#676e67]">{a.note}</div>}</div>)}{!item.logs.length&&<div className="mt-3 font-serif text-[11px] text-[#989a91]">まだ達成ログはありません。</div>}</section><div className="mt-5 grid gap-2 sm:grid-cols-2"><Link href={APP_ROUTES.knowledge} className="border border-[#9a8055]/20 py-3 text-center text-[11px] font-semibold text-[#75603d]">知をひらく</Link><button onClick={onAchieve} className="bg-[#1d241f] py-3 text-[11px] font-semibold text-[#eee6d8]">叶えた！を記録</button></div></div></div>}
function Box({label,values}:{label:string;values:string[]}){return <div className="border border-[#9a8055]/13 p-4"><div className="text-[9px] font-bold tracking-[.14em] text-[#8b8f87]">{label}</div><div className="mt-2 flex flex-wrap gap-1">{values.length?values.map(x=><span key={x} className="border border-[#9a8055]/13 px-2 py-1 text-[9px] text-[#777b73]">{x}</span>):<span className="text-[10px] text-[#9a9c94]">—</span>}</div></div>}
function AchievementModal({item,onSave,onClose}:{item:WantToSeed;onSave:(x:Omit<Achievement,'id'>)=>void;onClose:()=>void}){const[date,setDate]=useState(todayLocal());const[withWho,setWithWho]=useState('');const[place,setPlace]=useState('');const[satisfaction,setSatisfaction]=useState(5);const[repeat,setRepeat]=useState(5);const[note,setNote]=useState('');return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-[#090a08]/65 p-0 backdrop-blur-sm sm:items-center sm:p-4" onMouseDown={onClose}><form onSubmit={e=>{e.preventDefault();onSave({wantId:item.id,date,withWho,place,satisfaction,repeat,note})}} className="w-full max-w-lg border border-[#c8ab72]/20 bg-[#f4eee1] p-6" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><div className="text-[9px] font-bold tracking-[.2em] text-[#789581]">ACHIEVED</div><h2 className="mt-2 font-serif text-xl font-semibold leading-7">{item.title}</h2></div><button type="button" onClick={onClose} className="text-xl">×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="達成日"><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="誰と"><input value={withWho} onChange={e=>setWithWho(e.target.value)} placeholder="例：あいちゃん＋MAHRU"/></Field><Field label="場所・体験" wide><input value={place} onChange={e=>setPlace(e.target.value)} placeholder="例：箱根温泉"/></Field></div><Rating label="満足度" value={satisfaction} set={setSatisfaction}/><Rating label="またやりたい度" value={repeat} set={setRepeat}/><label className="mt-4 block text-[9px] font-bold tracking-wide text-[#80857d]">メモ<textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} className="mt-2 w-full border border-[#9a8055]/20 bg-[#faf6ed] p-3 text-sm font-normal outline-none" placeholder="気づき、新しく生まれたWant to"/></label><button type="submit" className="mt-5 w-full bg-[#1d241f] py-3 text-[11px] font-semibold text-[#eee6d8]">達成ログに追加</button></form></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactElement<{className?:string}>;wide?:boolean}){return <label className={`text-[9px] font-bold tracking-wide text-[#80857d] ${wide?'sm:col-span-2':''}`}>{label}<div className="mt-2 [&>input]:min-h-11 [&>input]:w-full [&>input]:border [&>input]:border-[#9a8055]/20 [&>input]:bg-[#faf6ed] [&>input]:px-3 [&>input]:text-sm [&>input]:font-normal [&>input]:outline-none">{children}</div></label>}
function Rating({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <div className="mt-4"><div className="text-[9px] font-bold tracking-wide text-[#80857d]">{label}</div><div className="mt-2 flex gap-2">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>set(n)} className={`h-10 w-10 rounded-full border text-sm font-semibold ${value===n?'border-[#9a8055] bg-[#c8ab72]/25 text-[#765b30]':'border-[#9a8055]/20 text-[#737971]'}`}>{n}</button>)}</div></div>}
