create table if not exists public.quest_catalog (
  id uuid primary key default gen_random_uuid(),
  quest_key text not null unique,
  capability text not null,
  phase_code text not null,
  phase_order integer not null,
  phase_item_order integer not null,
  global_order integer not null,
  age_band text not null,
  title text not null,
  instruction text not null,
  actor_mode text not null check (actor_mode in (
    'caregiver_led','caregiver_supported','adult_scaffolded',
    'guided_self','self_with_coach','self','self_or_coach'
  )),
  estimated_minutes integer not null check (estimated_minutes > 0),
  difficulty smallint not null default 1 check (difficulty between 1 and 5),
  xp_reward integer not null default 100 check (xp_reward >= 0),
  observation_axes text[] not null default '{}'::text[],
  tags text[] not null default '{}'::text[],
  recommendation_ref text not null unique,
  experience jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('draft','active','retired')),
  source_asset_id text,
  source_asset_title text,
  version text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (capability, phase_code, phase_item_order),
  unique (capability, global_order)
);

comment on table public.quest_catalog is
'Canonical reusable ACE Quest templates. Personal recommendations and completion history remain in education_recommendations/growth actions.';

create index if not exists quest_catalog_capability_phase_order_idx
  on public.quest_catalog(capability, status, phase_order, phase_item_order);

create index if not exists quest_catalog_tags_gin_idx
  on public.quest_catalog using gin(tags);

create index if not exists quest_catalog_observation_axes_gin_idx
  on public.quest_catalog using gin(observation_axes);

alter table public.quest_catalog enable row level security;

insert into public.quest_catalog
(quest_key, capability, phase_code, phase_order, phase_item_order, global_order,
 age_band, title, instruction, actor_mode, estimated_minutes, difficulty, xp_reward,
 observation_axes, tags, recommendation_ref, experience, status,
 source_asset_id, source_asset_title, version, metadata)
values
('SRQ001','self_regulation','P0A',0,1,1,'0〜18か月','まねっこ往復','表情、手拍子、声、簡単な動きを大人と交互に真似する。','caregiver_led',5,1,100,ARRAY['attention','action_planning']::text[],ARRAY['play','turn_taking','mimicry']::text[],'quest:self_regulation:SRQ001','{"intro": "大人が子どもの状態を観察し、安全で短い遊びとして行う。", "prediction": "始める前に、大人が今の子どもの身体・注意・感情の状態を一言で観察する。", "action": "表情、手拍子、声、簡単な動きを大人と交互に真似する。", "actual": "終わった直後の子どもの反応を、評価せず一つ記録する。", "reflection": "何に反応した？ どんな時に落ち着いた／興味が戻った？ 次は何を少し変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自分で整える前に「一緒に整ってもらう」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 01"}'::jsonb),
('SRQ002','self_regulation','P0A',0,2,2,'0〜18か月','いないいない・ばあ変化版','隠れる時間や場所を少しずつ変える。','caregiver_led',5,1,100,ARRAY['attention','impulse']::text[],ARRAY['play','prediction','waiting']::text[],'quest:self_regulation:SRQ002','{"intro": "大人が子どもの状態を観察し、安全で短い遊びとして行う。", "prediction": "始める前に、大人が今の子どもの身体・注意・感情の状態を一言で観察する。", "action": "隠れる時間や場所を少しずつ変える。", "actual": "終わった直後の子どもの反応を、評価せず一つ記録する。", "reflection": "何に反応した？ どんな時に落ち着いた／興味が戻った？ 次は何を少し変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自分で整える前に「一緒に整ってもらう」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 02"}'::jsonb),
('SRQ003','self_regulation','P0A',0,3,3,'0〜18か月','見つける遊び','玩具を布の下などに隠し、探す。','caregiver_led',5,1,100,ARRAY['attention','action_planning']::text[],ARRAY['play','memory','exploration']::text[],'quest:self_regulation:SRQ003','{"intro": "大人が子どもの状態を観察し、安全で短い遊びとして行う。", "prediction": "始める前に、大人が今の子どもの身体・注意・感情の状態を一言で観察する。", "action": "玩具を布の下などに隠し、探す。", "actual": "終わった直後の子どもの反応を、評価せず一つ記録する。", "reflection": "何に反応した？ どんな時に落ち着いた／興味が戻った？ 次は何を少し変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自分で整える前に「一緒に整ってもらう」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 03"}'::jsonb),
('SRQ004','self_regulation','P0A',0,4,4,'0〜18か月','名前をつけてもらう','「びっくりしたね」「眠くなったね」「音が大きかったね」と大人が状態を短く言語化する。','caregiver_led',3,1,100,ARRAY['body','emotion','meta']::text[],ARRAY['co_regulation','emotion_labeling','interoception']::text[],'quest:self_regulation:SRQ004','{"intro": "大人が子どもの状態を観察し、安全で短い遊びとして行う。", "prediction": "始める前に、大人が今の子どもの身体・注意・感情の状態を一言で観察する。", "action": "「びっくりしたね」「眠くなったね」「音が大きかったね」と大人が状態を短く言語化する。", "actual": "終わった直後の子どもの反応を、評価せず一つ記録する。", "reflection": "何に反応した？ どんな時に落ち着いた／興味が戻った？ 次は何を少し変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自分で整える前に「一緒に整ってもらう」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 04"}'::jsonb),
('SRQ005','self_regulation','P0B',1,1,5,'18〜36か月','GO / STOP','音楽や合図で動く→止まるを繰り返す。','caregiver_supported',5,1,100,ARRAY['attention','impulse','action_planning']::text[],ARRAY['play','inhibitory_control','switching']::text[],'quest:self_regulation:SRQ005','{"intro": "大人が合図や言葉を貸し、できた／できないより切り替えや再試行を観察する。", "prediction": "始める前に、大人が「今はやりたそう／休みたそう」など状態を短く予測する。", "action": "音楽や合図で動く→止まるを繰り返す。", "actual": "終わった直後に、切り替え・再試行・表情など実際の反応を一つ記録する。", "reflection": "何が切り替えの助けになった？ 次は大人の助けを一つ減らせそう？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情と行動に「名前」と簡単なルールが入る", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 05"}'::jsonb),
('SRQ006','self_regulation','P0B',1,2,6,'18〜36か月','ゆっくり／はやい','歩く、拍手、ボール転がしを速度変更する。','caregiver_supported',5,1,100,ARRAY['body','attention','action_planning']::text[],ARRAY['play','arousal_regulation','cognitive_flexibility']::text[],'quest:self_regulation:SRQ006','{"intro": "大人が合図や言葉を貸し、できた／できないより切り替えや再試行を観察する。", "prediction": "始める前に、大人が「今はやりたそう／休みたそう」など状態を短く予測する。", "action": "歩く、拍手、ボール転がしを速度変更する。", "actual": "終わった直後に、切り替え・再試行・表情など実際の反応を一つ記録する。", "reflection": "何が切り替えの助けになった？ 次は大人の助けを一つ減らせそう？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情と行動に「名前」と簡単なルールが入る", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 06"}'::jsonb),
('SRQ007','self_regulation','P0B',1,3,7,'18〜36か月','気持ち2択','「かなしい？くやしい？」「まだやりたい？休みたい？」と2択で言葉を貸す。','caregiver_supported',3,1,100,ARRAY['emotion','meta']::text[],ARRAY['emotion_labeling','choice','co_regulation']::text[],'quest:self_regulation:SRQ007','{"intro": "大人が合図や言葉を貸し、できた／できないより切り替えや再試行を観察する。", "prediction": "始める前に、大人が「今はやりたそう／休みたそう」など状態を短く予測する。", "action": "「かなしい？くやしい？」「まだやりたい？休みたい？」と2択で言葉を貸す。", "actual": "終わった直後に、切り替え・再試行・表情など実際の反応を一つ記録する。", "reflection": "何が切り替えの助けになった？ 次は大人の助けを一つ減らせそう？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情と行動に「名前」と簡単なルールが入る", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 07"}'::jsonb),
('SRQ008','self_regulation','P0B',1,4,8,'18〜36か月','お手伝い1ステップ','「これを箱に入れる」など短い役割を任せる。','caregiver_supported',5,1,100,ARRAY['attention','action_planning']::text[],ARRAY['working_memory','completion','self_efficacy']::text[],'quest:self_regulation:SRQ008','{"intro": "大人が合図や言葉を貸し、できた／できないより切り替えや再試行を観察する。", "prediction": "始める前に、大人が「今はやりたそう／休みたそう」など状態を短く予測する。", "action": "「これを箱に入れる」など短い役割を任せる。", "actual": "終わった直後に、切り替え・再試行・表情など実際の反応を一つ記録する。", "reflection": "何が切り替えの助けになった？ 次は大人の助けを一つ減らせそう？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情と行動に「名前」と簡単なルールが入る", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 08"}'::jsonb),
('SRQ009','self_regulation','P1',2,1,9,'3〜6歳','逆ルールゲーム','「赤と言ったら青を触る」など、慣れた反応と逆を選ぶ。','adult_scaffolded',7,2,200,ARRAY['attention','impulse','action_planning']::text[],ARRAY['play','inhibitory_control','cognitive_flexibility']::text[],'quest:self_regulation:SRQ009','{"intro": "大人が必要な足場だけを出し、本人が選ぶ余地を残して行う。", "prediction": "始める前に、本人に「できそう？むずかしそう？」を短く聞く。", "action": "「赤と言ったら青を触る」など、慣れた反応と逆を選ぶ。", "actual": "終わった直後に、できたこと／難しかったことを一つずつ拾う。", "reflection": "どこは自分でできた？ どこに助けが必要だった？ 次は何を自分で選ぶ？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "遊びの中で「自分を動かす」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 09"}'::jsonb),
('SRQ010','self_regulation','P1',2,2,10,'3〜6歳','ごっこ遊び作戦会議','遊ぶ前に「誰になる？何が必要？どう始める？」を決める。','adult_scaffolded',10,2,200,ARRAY['attention','action_planning','meta']::text[],ARRAY['play','planning','role_play']::text[],'quest:self_regulation:SRQ010','{"intro": "大人が必要な足場だけを出し、本人が選ぶ余地を残して行う。", "prediction": "始める前に、本人に「できそう？むずかしそう？」を短く聞く。", "action": "遊ぶ前に「誰になる？何が必要？どう始める？」を決める。", "actual": "終わった直後に、できたこと／難しかったことを一つずつ拾う。", "reflection": "どこは自分でできた？ どこに助けが必要だった？ 次は何を自分で選ぶ？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "遊びの中で「自分を動かす」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 10"}'::jsonb),
('SRQ011','self_regulation','P1',2,3,11,'3〜6歳','負けても続けるミニゲーム','勝敗のある短いゲーム後に「もう一回」「作戦変更」を選ぶ。','adult_scaffolded',10,2,200,ARRAY['emotion','impulse','action_planning']::text[],ARRAY['resilience','retry','game']::text[],'quest:self_regulation:SRQ011','{"intro": "大人が必要な足場だけを出し、本人が選ぶ余地を残して行う。", "prediction": "始める前に、本人に「できそう？むずかしそう？」を短く聞く。", "action": "勝敗のある短いゲーム後に「もう一回」「作戦変更」を選ぶ。", "actual": "終わった直後に、できたこと／難しかったことを一つずつ拾う。", "reflection": "どこは自分でできた？ どこに助けが必要だった？ 次は何を自分で選ぶ？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "遊びの中で「自分を動かす」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 11"}'::jsonb),
('SRQ012','self_regulation','P1',2,4,12,'3〜6歳','気持ち→身体マップ','怒った時の手、胸、お腹、顔などを絵や身体で表現する。','adult_scaffolded',10,2,200,ARRAY['body','emotion','meta']::text[],ARRAY['emotion_labeling','body_awareness','interoception']::text[],'quest:self_regulation:SRQ012','{"intro": "大人が必要な足場だけを出し、本人が選ぶ余地を残して行う。", "prediction": "始める前に、本人に「できそう？むずかしそう？」を短く聞く。", "action": "怒った時の手、胸、お腹、顔などを絵や身体で表現する。", "actual": "終わった直後に、できたこと／難しかったことを一つずつ拾う。", "reflection": "どこは自分でできた？ どこに助けが必要だった？ 次は何を自分で選ぶ？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "遊びの中で「自分を動かす」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 12"}'::jsonb),
('SRQ013','self_regulation','P1',2,5,13,'3〜6歳','3ステップお手伝い','「持ってくる→並べる→戻す」。必要なら絵カードで補助する。','adult_scaffolded',10,2,200,ARRAY['attention','action_planning']::text[],ARRAY['working_memory','sequence','scaffolding']::text[],'quest:self_regulation:SRQ013','{"intro": "大人が必要な足場だけを出し、本人が選ぶ余地を残して行う。", "prediction": "始める前に、本人に「できそう？むずかしそう？」を短く聞く。", "action": "「持ってくる→並べる→戻す」。必要なら絵カードで補助する。", "actual": "終わった直後に、できたこと／難しかったことを一つずつ拾う。", "reflection": "どこは自分でできた？ どこに助けが必要だった？ 次は何を自分で選ぶ？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "遊びの中で「自分を動かす」", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 13"}'::jsonb),
('SRQ014','self_regulation','P2A',3,1,14,'6〜9歳','自分の出発ルーティン','学校・練習前に「見る→持つ→確認」の3手順を本人が作る。','guided_self',10,2,200,ARRAY['attention','action_planning','meta']::text[],ARRAY['routine','planning','independence']::text[],'quest:self_regulation:SRQ014','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "学校・練習前に「見る→持つ→確認」の3手順を本人が作る。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "生活と遊びを「自分で回す」入口", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 14"}'::jsonb),
('SRQ015','self_regulation','P2A',3,2,15,'6〜9歳','10分集中→1分レビュー','短い課題後に「できた／気が散った／次どうする」を記録。','guided_self',11,2,200,ARRAY['attention','action_planning','meta']::text[],ARRAY['focus','reflection','retry']::text[],'quest:self_regulation:SRQ015','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "短い課題後に「できた／気が散った／次どうする」を記録。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "生活と遊びを「自分で回す」入口", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 15"}'::jsonb),
('SRQ016','self_regulation','P2A',3,3,16,'6〜9歳','ルール追加ゲーム','慣れた遊びに一つずつ条件を追加する。','guided_self',10,2,200,ARRAY['attention','impulse','action_planning']::text[],ARRAY['play','working_memory','cognitive_flexibility']::text[],'quest:self_regulation:SRQ016','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "慣れた遊びに一つずつ条件を追加する。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "生活と遊びを「自分で回す」入口", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 16"}'::jsonb),
('SRQ017','self_regulation','P2A',3,4,17,'6〜9歳','RESET動作をつくる','深呼吸、肩を回す、合言葉など「戻る動作」を本人と決める。','guided_self',10,2,200,ARRAY['body','emotion','action_planning','meta']::text[],ARRAY['reset','recovery','self_regulation']::text[],'quest:self_regulation:SRQ017','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "深呼吸、肩を回す、合言葉など「戻る動作」を本人と決める。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "生活と遊びを「自分で回す」入口", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N016"], "source_section": "Quest 17"}'::jsonb),
('SRQ018','self_regulation','P2B',4,1,18,'9〜12歳','3手先プラン','課題・スポーツ・遊びで「最初→次→もしダメなら」を考える。','guided_self',10,2,200,ARRAY['attention','action_planning','meta']::text[],ARRAY['planning','if_then','problem_solving']::text[],'quest:self_regulation:SRQ018','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "課題・スポーツ・遊びで「最初→次→もしダメなら」を考える。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "計画→実行→修正を自分で回す", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 18"}'::jsonb),
('SRQ019','self_regulation','P2B',4,2,19,'9〜12歳','作戦変更ポイント','ゲームや練習後に「どこで変えればよかった？」を一つ探す。','guided_self',10,2,200,ARRAY['action_planning','meta']::text[],ARRAY['reflection','strategy','adaptation']::text[],'quest:self_regulation:SRQ019','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "ゲームや練習後に「どこで変えればよかった？」を一つ探す。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "計画→実行→修正を自分で回す", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 19"}'::jsonb),
('SRQ020','self_regulation','P2B',4,3,20,'9〜12歳','自分の集中条件研究','場所、時間、音、姿勢、休憩条件を変え、集中しやすさを記録する。','guided_self',20,2,200,ARRAY['body','attention','meta']::text[],ARRAY['focus','environment_design','experiment']::text[],'quest:self_regulation:SRQ020','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "場所、時間、音、姿勢、休憩条件を変え、集中しやすさを記録する。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "計画→実行→修正を自分で回す", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 20"}'::jsonb),
('SRQ021','self_regulation','P2B',4,4,21,'9〜12歳','24時間ミッション','翌日の準備を前夜に本人が設計し、翌日レビューする。','guided_self',15,2,200,ARRAY['attention','action_planning','meta']::text[],ARRAY['planning','review','independence']::text[],'quest:self_regulation:SRQ021','{"intro": "本人が主役。大人は答えを先回りせず、必要な時だけ問いや補助を出す。", "prediction": "始める前に、どうなりそうかを一言で予想する。", "action": "翌日の準備を前夜に本人が設計し、翌日レビューする。", "actual": "実際にどうなったかを一つ記録する。", "reflection": "予想と実際はどう違った？ 次に同じ場面が来たら何を変える？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "計画→実行→修正を自分で回す", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 21"}'::jsonb),
('SRQ022','self_regulation','P3A',5,1,22,'12〜15歳','90秒PAUSE','強い感情時に「反応しない時間」をつくり、身体感覚を観察する。','self_with_coach',5,2,200,ARRAY['body','emotion','impulse','meta']::text[],ARRAY['pause','emotion_regulation','interoception']::text[],'quest:self_regulation:SRQ022','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "強い感情時に「反応しない時間」をつくり、身体感覚を観察する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情・仲間・衝動の中で「自分の選択」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 22"}'::jsonb),
('SRQ023','self_regulation','P3A',5,2,23,'12〜15歳','事実／解釈／感情','出来事を3列で書き分ける。','self_with_coach',10,2,200,ARRAY['emotion','meta']::text[],ARRAY['cognition','emotion_labeling','reflection']::text[],'quest:self_regulation:SRQ023','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "出来事を3列で書き分ける。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情・仲間・衝動の中で「自分の選択」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N001"], "source_section": "Quest 23"}'::jsonb),
('SRQ024','self_regulation','P3A',5,3,24,'12〜15歳','スマホ環境実験','通知ON/OFF、置き場所、時間帯を1週間ずつ変えて、自分の集中を比較する。','self_with_coach',15,3,300,ARRAY['attention','impulse','action_planning','meta']::text[],ARRAY['digital','environment_design','experiment']::text[],'quest:self_regulation:SRQ024','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "通知ON/OFF、置き場所、時間帯を1週間ずつ変えて、自分の集中を比較する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情・仲間・衝動の中で「自分の選択」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 24"}'::jsonb),
('SRQ025','self_regulation','P3A',5,4,25,'12〜15歳','Peer Pressure Replay','「みんながやるから」の場面を想定し、自分の選択肢を3つ作る。','self_with_coach',15,3,300,ARRAY['emotion','impulse','action_planning','meta']::text[],ARRAY['peer_pressure','choice','rehearsal']::text[],'quest:self_regulation:SRQ025','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "「みんながやるから」の場面を想定し、自分の選択肢を3つ作る。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情・仲間・衝動の中で「自分の選択」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 25"}'::jsonb),
('SRQ026','self_regulation','P3A',5,5,26,'12〜15歳','試合・テストRESET','ミス後に行う身体動作＋言葉＋次の一点を固定する。','self_with_coach',15,3,300,ARRAY['body','emotion','attention','action_planning','meta']::text[],ARRAY['reset','performance','recovery']::text[],'quest:self_regulation:SRQ026','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "ミス後に行う身体動作＋言葉＋次の一点を固定する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "感情・仲間・衝動の中で「自分の選択」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N016"], "source_section": "Quest 26"}'::jsonb),
('SRQ027','self_regulation','P3B',6,1,27,'15〜18歳','Project Breakdown','30日以内の目標を、週→日→最初の15分に分解する。','self_with_coach',20,3,300,ARRAY['attention','action_planning','meta']::text[],ARRAY['planning','project','execution']::text[],'quest:self_regulation:SRQ027','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "30日以内の目標を、週→日→最初の15分に分解する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "目標・時間・誘惑を自分でマネジメントする", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 27"}'::jsonb),
('SRQ028','self_regulation','P3B',6,2,28,'15〜18歳','集中前ルーティン','机、スマホ、飲み物、呼吸、最初の作業を固定する。','self_with_coach',15,2,200,ARRAY['body','attention','action_planning']::text[],ARRAY['focus','routine','environment_design']::text[],'quest:self_regulation:SRQ028','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "机、スマホ、飲み物、呼吸、最初の作業を固定する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "目標・時間・誘惑を自分でマネジメントする", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 28"}'::jsonb),
('SRQ029','self_regulation','P3B',6,3,29,'15〜18歳','Energy Log','時間ではなく「集中しやすい時間帯／疲れる条件」を7日間記録。','self_with_coach',10,2,200,ARRAY['body','attention','meta']::text[],ARRAY['energy','tracking','self_knowledge']::text[],'quest:self_regulation:SRQ029','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "時間ではなく「集中しやすい時間帯／疲れる条件」を7日間記録。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "目標・時間・誘惑を自分でマネジメントする", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 29"}'::jsonb),
('SRQ030','self_regulation','P3B',6,4,30,'15〜18歳','Weekly Reset','週1回、KEEP／STOP／STARTの3項目だけ振り返る。','self_with_coach',15,2,200,ARRAY['action_planning','meta']::text[],ARRAY['weekly_review','reset','reflection']::text[],'quest:self_regulation:SRQ030','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "週1回、KEEP／STOP／STARTの3項目だけ振り返る。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "目標・時間・誘惑を自分でマネジメントする", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 30"}'::jsonb),
('SRQ031','self_regulation','P3B',6,5,31,'15〜18歳','Pressure Simulation','試合・面接・試験前に本番条件を模して、リセット方法を練習する。','self_with_coach',30,3,300,ARRAY['body','emotion','attention','action_planning','meta']::text[],ARRAY['pressure','simulation','performance']::text[],'quest:self_regulation:SRQ031','{"intro": "本人が実験者。親・先生・コーチは管理ではなく振り返り支援を行う。", "prediction": "始める前に、今の状態と結果予想を0〜4または一文で置く。", "action": "試合・面接・試験前に本番条件を模して、リセット方法を練習する。", "actual": "実行後の結果と状態の変化を一つずつ記録する。", "reflection": "感情や衝動と行動の間に、どんな選択肢が増えた？ 次の実験は何にする？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "目標・時間・誘惑を自分でマネジメントする", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N016"], "source_section": "Quest 31"}'::jsonb),
('SRQ032','self_regulation','P4',7,1,32,'18〜25歳前後','自分OS監査','睡眠、食事、運動、デジタル、仕事、学習、人間関係を0〜10で自己評価し、最小ボトルネックを一つ選ぶ。','self',20,3,300,ARRAY['body','emotion','attention','action_planning','meta']::text[],ARRAY['life_os','audit','bottleneck']::text[],'quest:self_regulation:SRQ032','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "睡眠、食事、運動、デジタル、仕事、学習、人間関係を0〜10で自己評価し、最小ボトルネックを一つ選ぶ。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自由の増加に合わせて「自分の生活OS」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 32"}'::jsonb),
('SRQ033','self_regulation','P4',7,2,33,'18〜25歳前後','摩擦デザイン','やりたい行動は摩擦を減らす。減らしたい行動は摩擦を増やす。例：朝運動の服を前夜に出す／SNSをホーム画面から外す。','self',20,3,300,ARRAY['impulse','action_planning','meta']::text[],ARRAY['behavior_design','friction','environment_design']::text[],'quest:self_regulation:SRQ033','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "やりたい行動は摩擦を減らす。減らしたい行動は摩擦を増やす。例：朝運動の服を前夜に出す／SNSをホーム画面から外す。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自由の増加に合わせて「自分の生活OS」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 33"}'::jsonb),
('SRQ034','self_regulation','P4',7,3,34,'18〜25歳前後','24時間後ルール','感情が強い大きな決断は可能なら一晩置き、翌日に再評価する。','self',10,2,200,ARRAY['emotion','impulse','meta']::text[],ARRAY['decision','pause','emotion_regulation']::text[],'quest:self_regulation:SRQ034','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "感情が強い大きな決断は可能なら一晩置き、翌日に再評価する。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自由の増加に合わせて「自分の生活OS」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 34"}'::jsonb),
('SRQ035','self_regulation','P4',7,4,35,'18〜25歳前後','週次CEO Meeting','自分を一つのチームとして、成果・身体・感情・関係・次週の一点をレビューする。','self',30,3,300,ARRAY['body','emotion','action_planning','meta']::text[],ARRAY['weekly_review','leadership','self_management']::text[],'quest:self_regulation:SRQ035','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "自分を一つのチームとして、成果・身体・感情・関係・次週の一点をレビューする。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "自由の増加に合わせて「自分の生活OS」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 35"}'::jsonb),
('SRQ036','self_regulation','P5',8,1,36,'成人期','Role Switch Ritual','仕事→家庭、競技→仕事など、役割切替時の3分ルーティンを作る。','self',10,2,200,ARRAY['body','emotion','attention','action_planning']::text[],ARRAY['role_switch','transition','routine']::text[],'quest:self_regulation:SRQ036','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "仕事→家庭、競技→仕事など、役割切替時の3分ルーティンを作る。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "成果・健康・家族・Purposeを統合する", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 36"}'::jsonb),
('SRQ037','self_regulation','P5',8,2,37,'成人期','Stress Signal List','自分の崩れ始めのサインを身体・感情・行動で3つずつ言語化する。','self',20,3,300,ARRAY['body','emotion','action_planning','meta']::text[],ARRAY['stress','early_signal','self_knowledge']::text[],'quest:self_regulation:SRQ037','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "自分の崩れ始めのサインを身体・感情・行動で3つずつ言語化する。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "成果・健康・家族・Purposeを統合する", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 37"}'::jsonb),
('SRQ038','self_regulation','P5',8,3,38,'成人期','Minimum Viable Day','調子が悪い日でも守る最小行動を決める。例：10分歩く、重要連絡1件、睡眠時刻だけ守る。','self',15,2,200,ARRAY['body','emotion','action_planning','meta']::text[],ARRAY['minimum_viable_day','recovery','resilience']::text[],'quest:self_regulation:SRQ038','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "調子が悪い日でも守る最小行動を決める。例：10分歩く、重要連絡1件、睡眠時刻だけ守る。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "成果・健康・家族・Purposeを統合する", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 38"}'::jsonb),
('SRQ039','self_regulation','P5',8,4,39,'成人期','Delegation Quest','今週、自分でなくてもよいことを一つ手放す。','self',20,3,300,ARRAY['action_planning','meta']::text[],ARRAY['delegation','load_management','leadership']::text[],'quest:self_regulation:SRQ039','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "今週、自分でなくてもよいことを一つ手放す。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "成果・健康・家族・Purposeを統合する", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 39"}'::jsonb),
('SRQ040','self_regulation','P5',8,5,40,'成人期','Quarter Reset','3か月ごとに、続ける／やめる／始める／任せるを再設計する。','self',30,3,300,ARRAY['action_planning','meta']::text[],ARRAY['quarter_review','reset','prioritization']::text[],'quest:self_regulation:SRQ040','{"intro": "自分の状態と環境を観察し、最小の実験として実行する。", "prediction": "始める前に、今の状態と予想を短く記録する。", "action": "3か月ごとに、続ける／やめる／始める／任せるを再設計する。", "actual": "実行後の結果、状態、次に変える条件を短く記録する。", "reflection": "意志力ではなく、どの条件を変えるともっと自然に回る？ 次の一手は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "成果・健康・家族・Purposeを統合する", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 40"}'::jsonb),
('SRQ041','self_regulation','P6',9,1,41,'転換・再起期','旧OS棚卸し','以前うまくいっていた習慣・環境・人間関係を書き、「今も使える／変える／手放す」に分類する。','self_or_coach',30,3,300,ARRAY['emotion','action_planning','meta']::text[],ARRAY['transition','unlearn','life_os']::text[],'quest:self_regulation:SRQ041','{"intro": "本人またはコーチと、過去への評価ではなく次の再設計のために行う。", "prediction": "始める前に、今の状態と「何が少し変われば前に進めるか」を一文で置く。", "action": "以前うまくいっていた習慣・環境・人間関係を書き、「今も使える／変える／手放す」に分類する。", "actual": "実行後に「起きた事実／変わったこと／次の一手」を短く記録する。", "reflection": "以前の自分に戻るのではなく、今の自分に合う戻り方・進み方は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "以前の自分に戻るのではなく「新しい自分の調整系」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 41"}'::jsonb),
('SRQ042','self_regulation','P6',9,2,42,'転換・再起期','Small Fact','24時間以内に作れる小さな事実を一つ作る。例：1件連絡、10分運動、資料1ページ、応募1件。','self_or_coach',15,2,200,ARRAY['action_planning','meta']::text[],ARRAY['small_fact','action','self_efficacy']::text[],'quest:self_regulation:SRQ042','{"intro": "本人またはコーチと、過去への評価ではなく次の再設計のために行う。", "prediction": "始める前に、今の状態と「何が少し変われば前に進めるか」を一文で置く。", "action": "24時間以内に作れる小さな事実を一つ作る。例：1件連絡、10分運動、資料1ページ、応募1件。", "actual": "実行後に「起きた事実／変わったこと／次の一手」を短く記録する。", "reflection": "以前の自分に戻るのではなく、今の自分に合う戻り方・進み方は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "以前の自分に戻るのではなく「新しい自分の調整系」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 42"}'::jsonb),
('SRQ043','self_regulation','P6',9,3,43,'転換・再起期','経験→能力翻訳','過去の経験を「何をしたか」ではなく「何を身につけたか」に翻訳する。','self_or_coach',30,3,300,ARRAY['emotion','action_planning','meta']::text[],ARRAY['experience_asset','translation','identity']::text[],'quest:self_regulation:SRQ043','{"intro": "本人またはコーチと、過去への評価ではなく次の再設計のために行う。", "prediction": "始める前に、今の状態と「何が少し変われば前に進めるか」を一文で置く。", "action": "過去の経験を「何をしたか」ではなく「何を身につけたか」に翻訳する。", "actual": "実行後に「起きた事実／変わったこと／次の一手」を短く記録する。", "reflection": "以前の自分に戻るのではなく、今の自分に合う戻り方・進み方は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "以前の自分に戻るのではなく「新しい自分の調整系」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N004"], "source_section": "Quest 43"}'::jsonb),
('SRQ044','self_regulation','P6',9,4,44,'転換・再起期','New Identity Trial','新しい役割を“小さく試す”。肩書きを決める前に行動実験を行う。','self_or_coach',30,3,300,ARRAY['emotion','action_planning','meta']::text[],ARRAY['identity','experiment','action']::text[],'quest:self_regulation:SRQ044','{"intro": "本人またはコーチと、過去への評価ではなく次の再設計のために行う。", "prediction": "始める前に、今の状態と「何が少し変われば前に進めるか」を一文で置く。", "action": "新しい役割を“小さく試す”。肩書きを決める前に行動実験を行う。", "actual": "実行後に「起きた事実／変わったこと／次の一手」を短く記録する。", "reflection": "以前の自分に戻るのではなく、今の自分に合う戻り方・進み方は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "以前の自分に戻るのではなく「新しい自分の調整系」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": [], "source_section": "Quest 44"}'::jsonb),
('SRQ045','self_regulation','P6',9,5,45,'転換・再起期','Return Protocol','落ちた時に戻る順序を固定する。Body → Environment → One Action → Reflection → Reconnect。','self_or_coach',15,3,300,ARRAY['body','emotion','attention','action_planning','meta']::text[],ARRAY['return_protocol','reset','reconnect']::text[],'quest:self_regulation:SRQ045','{"intro": "本人またはコーチと、過去への評価ではなく次の再設計のために行う。", "prediction": "始める前に、今の状態と「何が少し変われば前に進めるか」を一文で置く。", "action": "落ちた時に戻る順序を固定する。Body → Environment → One Action → Reflection → Reconnect。", "actual": "実行後に「起きた事実／変わったこと／次の一手」を短く記録する。", "reflection": "以前の自分に戻るのではなく、今の自分に合う戻り方・進み方は何？"}'::jsonb,'active','15aNW0c5DNGa5wc8AbBu4orxtwLsGT977_ibsEnzZYlc','ACE教材｜自己調整力 Development Curriculum｜0歳〜成人・転換期｜2026-09-04','self-regulation-v1','{"phase_title": "以前の自分に戻るのではなく「新しい自分の調整系」をつくる", "canonical_loop": ["NOTICE", "PAUSE", "NAME", "CHOOSE", "ACT", "REVIEW_RESET"], "related_node_ids": ["N016"], "source_section": "Quest 45"}'::jsonb)
on conflict (quest_key) do update set
  capability = excluded.capability,
  phase_code = excluded.phase_code,
  phase_order = excluded.phase_order,
  phase_item_order = excluded.phase_item_order,
  global_order = excluded.global_order,
  age_band = excluded.age_band,
  title = excluded.title,
  instruction = excluded.instruction,
  actor_mode = excluded.actor_mode,
  estimated_minutes = excluded.estimated_minutes,
  difficulty = excluded.difficulty,
  xp_reward = excluded.xp_reward,
  observation_axes = excluded.observation_axes,
  tags = excluded.tags,
  recommendation_ref = excluded.recommendation_ref,
  experience = excluded.experience,
  status = excluded.status,
  source_asset_id = excluded.source_asset_id,
  source_asset_title = excluded.source_asset_title,
  version = excluded.version,
  metadata = excluded.metadata,
  updated_at = now();